// backend/src/utils/airportCodes.js

/**
 * Mapeo de ciudades a códigos de aeropuerto IATA
 * Formato: 'NOMBRE_CIUDAD_VARIANTE': 'CODIGO_IATA'
 * 
 * Fuente: IATA Official Codes + Common Variants
 * Última actualización: 2026
 */


const AIRPORT_CODES = {
  // ===========================================
  // 🇺🇸 USA - Principal Airports
  // ===========================================
  'NEW YORK': 'JFK',
  'NYC': 'JFK',
  'NEW YORK, USA': 'JFK',
  'NEW YORK, NY': 'JFK',
  'NEW YORK CITY': 'JFK',
  'MANHATTAN': 'JFK',
  'BROOKLYN': 'JFK',
  'QUEENS': 'JFK',
  'TIJUANA': 'TIJ',
  'TIJUANA, MEXICO': 'TIJ',
  
  'LOS ANGELES': 'LAX',
  'LA': 'LAX',
  'LOS ANGELES, USA': 'LAX',
  'Los Angeles, USA': 'LAX',
  'LOS ANGELES, CA': 'LAX',
  'LOS ANGELES, CALIFORNIA': 'LAX',
  'HOLLYWOOD': 'LAX',
  'BEVERLY HILLS': 'LAX',
  'SANTA MONICA': 'LAX',
  
  'CHICAGO': 'ORD',
  'CHICAGO, USA': 'ORD',
  'CHICAGO, IL': 'ORD',
  'CHICAGO, ILLINOIS': 'ORD',
  
  'SAN FRANCISCO': 'SFO',
  'SAN FRANCISCO, USA': 'SFO',
  'SAN FRANCISCO, CA': 'SFO',
  'SAN FRANCISCO, CALIFORNIA': 'SFO',
  'SF': 'SFO',
  'BAY AREA': 'SFO',
  
  'SEATTLE': 'SEA',
  'SEATTLE, USA': 'SEA',
  'SEATTLE, WA': 'SEA',
  'SEATTLE, WASHINGTON': 'SEA',
  
  'MIAMI': 'MIA',
  'MIAMI, USA': 'MIA',
  'MIAMI, FL': 'MIA',
  'MIAMI, FLORIDA': 'MIA',
  'SOUTH BEACH': 'MIA',
  
  'BOSTON': 'BOS',
  'BOSTON, USA': 'BOS',
  'BOSTON, MA': 'BOS',
  'BOSTON, MASSACHUSETTS': 'BOS',
  
  'DALLAS': 'DFW',
  'DALLAS, USA': 'DFW',
  'DALLAS, TX': 'DFW',
  'DALLAS, TEXAS': 'DFW',
  'FORT WORTH': 'DFW',
  
  'HOUSTON': 'IAH',
  'HOUSTON, USA': 'IAH',
  'HOUSTON, TX': 'IAH',
  'HOUSTON, TEXAS': 'IAH',
  
  'DENVER': 'DEN',
  'DENVER, USA': 'DEN',
  'DENVER, CO': 'DEN',
  'DENVER, COLORADO': 'DEN',
  
  'LAS VEGAS': 'LAS',
  'LAS VEGAS, USA': 'LAS',
  'LAS VEGAS, NV': 'LAS',
  'LAS VEGAS, NEVADA': 'LAS',
  'VEGAS': 'LAS',
  
  'ORLANDO': 'MCO',
  'ORLANDO, USA': 'MCO',
  'ORLANDO, FL': 'MCO',
  'ORLANDO, FLORIDA': 'MCO',
  'DISNEY WORLD': 'MCO',
  'UNIVERSAL STUDIOS': 'MCO',
  
  'ATLANTA': 'ATL',
  'ATLANTA, USA': 'ATL',
  'ATLANTA, GA': 'ATL',
  'ATLANTA, GEORGIA': 'ATL',
  
  'PHOENIX': 'PHX',
  'PHOENIX, USA': 'PHX',
  'PHOENIX, AZ': 'PHX',
  'PHOENIX, ARIZONA': 'PHX',
  
  'WASHINGTON': 'IAD',
  'WASHINGTON, USA': 'IAD',
  'WASHINGTON, DC': 'IAD',
  'DC': 'IAD',
  'DISTRICT OF COLUMBIA': 'IAD',
  'CAPITOL': 'IAD',
  
  'WASHINGTON DULLES': 'IAD',
  'DULLES': 'IAD',

  // ✅ NUEVAS CIUDADES USA AGREGADAS
  'SAN DIEGO': 'SAN',
  'SAN DIEGO, USA': 'SAN',
  'SAN DIEGO, CA': 'SAN',
  'SAN DIEGO, CALIFORNIA': 'SAN',
  
  'PORTLAND': 'PDX',
  'PORTLAND, USA': 'PDX',
  'PORTLAND, OR': 'PDX',
  'PORTLAND, OREGON': 'PDX',
  
  'AUSTIN': 'AUS',
  'AUSTIN, USA': 'AUS',
  'AUSTIN, TX': 'AUS',
  'AUSTIN, TEXAS': 'AUS',
  
  'NASHVILLE': 'BNA',
  'NASHVILLE, USA': 'BNA',
  'NASHVILLE, TN': 'BNA',
  'NASHVILLE, TENNESSEE': 'BNA',
  
  'NEW ORLEANS': 'MSY',
  'NEW ORLEANS, USA': 'MSY',
  'NEW ORLEANS, LA': 'MSY',
  'NEW ORLEANS, LOUISIANA': 'MSY',
  
  'TAMPA': 'TPA',
  'TAMPA, USA': 'TPA',
  'TAMPA, FL': 'TPA',
  'TAMPA, FLORIDA': 'TPA',
  
  'CHARLOTTE': 'CLT',
  'CHARLOTTE, USA': 'CLT',
  'CHARLOTTE, NC': 'CLT',
  'CHARLOTTE, NORTH CAROLINA': 'CLT',
  
  'MINNEAPOLIS': 'MSP',
  'MINNEAPOLIS, USA': 'MSP',
  'MINNEAPOLIS, MN': 'MSP',
  'MINNEAPOLIS, MINNESOTA': 'MSP',
  
  'DETROIT': 'DTW',
  'DETROIT, USA': 'DTW',
  'DETROIT, MI': 'DTW',
  'DETROIT, MICHIGAN': 'DTW',
  
  'PHILADELPHIA': 'PHL',
  'PHILADELPHIA, USA': 'PHL',
  'PHILADELPHIA, PA': 'PHL',
  'PHILADELPHIA, PENNSYLVANIA': 'PHL',
  'PHILA': 'PHL',
  
  'BALTIMORE': 'BWI',
  'BALTIMORE, USA': 'BWI',
  'BALTIMORE, MD': 'BWI',
  'BALTIMORE, MARYLAND': 'BWI',
  
  'PITTSBURGH': 'PIT',
  'PITTSBURGH, USA': 'PIT',
  'PITTSBURGH, PA': 'PIT',
  'PITTSBURGH, PENNSYLVANIA': 'PIT',
  
  'CLEVELAND': 'CLE',
  'CLEVELAND, USA': 'CLE',
  'CLEVELAND, OH': 'CLE',
  'CLEVELAND, OHIO': 'CLE',
  
  'CINCINNATI': 'CVG',
  'CINCINNATI, USA': 'CVG',
  'CINCINNATI, OH': 'CVG',
  'CINCINNATI, OHIO': 'CVG',
  
  'KANSAS CITY': 'MCI',
  'KANSAS CITY, USA': 'MCI',
  'KANSAS CITY, MO': 'MCI',
  'KANSAS CITY, MISSOURI': 'MCI',
  
  'ST. LOUIS': 'STL',
  'ST LOUIS': 'STL',
  'ST. LOUIS, USA': 'STL',
  'ST LOUIS, USA': 'STL',
  'ST. LOUIS, MO': 'STL',
  'ST LOUIS, MO': 'STL',
  'ST. LOUIS, MISSOURI': 'STL',
  
  'MILWAUKEE': 'MKE',
  'MILWAUKEE, USA': 'MKE',
  'MILWAUKEE, WI': 'MKE',
  'MILWAUKEE, WISCONSIN': 'MKE',
  
  'INDIANAPOLIS': 'IND',
  'INDIANAPOLIS, USA': 'IND',
  'INDIANAPOLIS, IN': 'IND',
  'INDIANAPOLIS, INDIANA': 'IND',
  
  'COLUMBUS': 'CMH',
  'COLUMBUS, USA': 'CMH',
  'COLUMBUS, OH': 'CMH',
  'COLUMBUS, OHIO': 'CMH',
  
  'RALEIGH': 'RDU',
  'RALEIGH, USA': 'RDU',
  'RALEIGH, NC': 'RDU',
  'RALEIGH, NORTH CAROLINA': 'RDU',
  
  'SALT LAKE CITY': 'SLC',
  'SALT LAKE CITY, USA': 'SLC',
  'SALT LAKE CITY, UT': 'SLC',
  'SALT LAKE CITY, UTAH': 'SLC',
  'SLC': 'SLC',
  
  'BOISE': 'BOI',
  'BOISE, USA': 'BOI',
  'BOISE, ID': 'BOI',
  'BOISE, IDAHO': 'BOI',
  
  'RENO': 'RNO',
  'RENO, USA': 'RNO',
  'RENO, NV': 'RNO',
  'RENO, NEVADA': 'RNO',
  
  'TUCSON': 'TUS',
  'TUCSON, USA': 'TUS',
  'TUCSON, AZ': 'TUS',
  'TUCSON, ARIZONA': 'TUS',
  
  'ALBUQUERQUE': 'ABQ',
  'ALBUQUERQUE, USA': 'ABQ',
  'ALBUQUERQUE, NM': 'ABQ',
  'ALBUQUERQUE, NEW MEXICO': 'ABQ',
  
  'OKLAHOMA CITY': 'OKC',
  'OKLAHOMA CITY, USA': 'OKC',
  'OKLAHOMA CITY, OK': 'OKC',
  'OKLAHOMA CITY, OKLAHOMA': 'OKC',
  
  'MEMPHIS': 'MEM',
  'MEMPHIS, USA': 'MEM',
  'MEMPHIS, TN': 'MEM',
  'MEMPHIS, TENNESSEE': 'MEM',
  
  'LOUISVILLE': 'SDF',
  'LOUISVILLE, USA': 'SDF',
  'LOUISVILLE, KY': 'SDF',
  'LOUISVILLE, KENTUCKY': 'SDF',
  
  'RICHMOND': 'RIC',
  'RICHMOND, USA': 'RIC',
  'RICHMOND, VA': 'RIC',
  'RICHMOND, VIRGINIA': 'RIC',
  
  'BUFFALO': 'BUF',
  'BUFFALO, USA': 'BUF',
  'BUFFALO, NY': 'BUF',
  'BUFFALO, NEW YORK': 'BUF',
  
  'ROCHESTER': 'ROC',
  'ROCHESTER, USA': 'ROC',
  'ROCHESTER, NY': 'ROC',
  'ROCHESTER, NEW YORK': 'ROC',
  
  'HARTFORD': 'BDL',
  'HARTFORD, USA': 'BDL',
  'HARTFORD, CT': 'BDL',
  'HARTFORD, CONNECTICUT': 'BDL',
  
  'PROVIDENCE': 'PVD',
  'PROVIDENCE, USA': 'PVD',
  'PROVIDENCE, RI': 'PVD',
  'PROVIDENCE, RHODE ISLAND': 'PVD',
  
  'MANCHESTER': 'MHT',
  'MANCHESTER, USA': 'MHT',
  'MANCHESTER, NH': 'MHT',
  'MANCHESTER, NEW HAMPSHIRE': 'MHT',
  
  'BURLINGTON': 'BTV',
  'BURLINGTON, USA': 'BTV',
  'BURLINGTON, VT': 'BTV',
  'BURLINGTON, VERMONT': 'BTV',
  
  'JACKSONVILLE': 'JAX',
  'JACKSONVILLE, USA': 'JAX',
  'JACKSONVILLE, FL': 'JAX',
  'JACKSONVILLE, FLORIDA': 'JAX',
  
  'FORT LAUDERDALE': 'FLL',
  'FORT LAUDERDALE, USA': 'FLL',
  'FORT LAUDERDALE, FL': 'FLL',
  'FORT LAUDERDALE, FLORIDA': 'FLL',
  
  'WEST PALM BEACH': 'PBI',
  'WEST PALM BEACH, USA': 'PBI',
  'WEST PALM BEACH, FL': 'PBI',
  'WEST PALM BEACH, FLORIDA': 'PBI',
  
  'SARASOTA': 'SRQ',
  'SARASOTA, USA': 'SRQ',
  'SARASOTA, FL': 'SRQ',
  'SARASOTA, FLORIDA': 'SRQ',
  
  'FORT MYERS': 'RSW',
  'FORT MYERS, USA': 'RSW',
  'FORT MYERS, FL': 'RSW',
  'FORT MYERS, FLORIDA': 'RSW',
  
  'KEY WEST': 'EYW',
  'KEY WEST, USA': 'EYW',
  'KEY WEST, FL': 'EYW',
  'KEY WEST, FLORIDA': 'EYW',
  
  'MYRTLE BEACH': 'MYR',
  'MYRTLE BEACH, USA': 'MYR',
  'MYRTLE BEACH, SC': 'MYR',
  'MYRTLE BEACH, SOUTH CAROLINA': 'MYR',
  
  'CHARLESTON': 'CHS',
  'CHARLESTON, USA': 'CHS',
  'CHARLESTON, SC': 'CHS',
  'CHARLESTON, SOUTH CAROLINA': 'CHS',
  
  'SAVANNAH': 'SAV',
  'SAVANNAH, USA': 'SAV',
  'SAVANNAH, GA': 'SAV',
  'SAVANNAH, GEORGIA': 'SAV',
  
  'ASHEVILLE': 'AVL',
  'ASHEVILLE, USA': 'AVL',
  'ASHEVILLE, NC': 'AVL',
  'ASHEVILLE, NORTH CAROLINA': 'AVL',
  
  'KNOXVILLE': 'TYS',
  'KNOXVILLE, USA': 'TYS',
  'KNOXVILLE, TN': 'TYS',
  'KNOXVILLE, TENNESSEE': 'TYS',
  
  'CHATTANOOGA': 'CHA',
  'CHATTANOOGA, USA': 'CHA',
  'CHATTANOOGA, TN': 'CHA',
  'CHATTANOOGA, TENNESSEE': 'CHA',
  
  'BIRMINGHAM': 'BHM',
  'BIRMINGHAM, USA': 'BHM',
  'BIRMINGHAM, AL': 'BHM',
  'BIRMINGHAM, ALABAMA': 'BHM',
  
  'MOBILE': 'MOB',
  'MOBILE, USA': 'MOB',
  'MOBILE, AL': 'MOB',
  'MOBILE, ALABAMA': 'MOB',
  
  'JACKSON': 'JAN',
  'JACKSON, USA': 'JAN',
  'JACKSON, MS': 'JAN',
  'JACKSON, MISSISSIPPI': 'JAN',
  
  'LITTLE ROCK': 'LIT',
  'LITTLE ROCK, USA': 'LIT',
  'LITTLE ROCK, AR': 'LIT',
  'LITTLE ROCK, ARKANSAS': 'LIT',
  
  'TULSA': 'TUL',
  'TULSA, USA': 'TUL',
  'TULSA, OK': 'TUL',
  'TULSA, OKLAHOMA': 'TUL',
  
  'WICHITA': 'ICT',
  'WICHITA, USA': 'ICT',
  'WICHITA, KS': 'ICT',
  'WICHITA, KANSAS': 'ICT',
  
  'OMAHA': 'OMA',
  'OMAHA, USA': 'OMA',
  'OMAHA, NE': 'OMA',
  'OMAHA, NEBRASKA': 'OMA',
  
  'DES MOINES': 'DSM',
  'DES MOINES, USA': 'DSM',
  'DES MOINES, IA': 'DSM',
  'DES MOINES, IOWA': 'DSM',
  
  'SIOUX FALLS': 'FSD',
  'SIOUX FALLS, USA': 'FSD',
  'SIOUX FALLS, SD': 'FSD',
  'SIOUX FALLS, SOUTH DAKOTA': 'FSD',
  
  'FARGO': 'FAR',
  'FARGO, USA': 'FAR',
  'FARGO, ND': 'FAR',
  'FARGO, NORTH DAKOTA': 'FAR',
  
  'BILLINGS': 'BIL',
  'BILLINGS, USA': 'BIL',
  'BILLINGS, MT': 'BIL',
  'BILLINGS, MONTANA': 'BIL',
  
  'BOZEMAN': 'BZN',
  'BOZEMAN, USA': 'BZN',
  'BOZEMAN, MT': 'BZN',
  'BOZEMAN, MONTANA': 'BZN',
  
  'MISSOULA': 'MSO',
  'MISSOULA, USA': 'MSO',
  'MISSOULA, MT': 'MSO',
  'MISSOULA, MONTANA': 'MSO',
  
  'SPOKANE': 'GEG',
  'SPOKANE, USA': 'GEG',
  'SPOKANE, WA': 'GEG',
  'SPOKANE, WASHINGTON': 'GEG',
  
  'EUGENE': 'EUG',
  'EUGENE, USA': 'EUG',
  'EUGENE, OR': 'EUG',
  'EUGENE, OREGON': 'EUG',
  
  'MEDFORD': 'MFR',
  'MEDFORD, USA': 'MFR',
  'MEDFORD, OR': 'MFR',
  'MEDFORD, OREGON': 'MFR',
  
  'REDDING': 'RDD',
  'REDDING, USA': 'RDD',
  'REDDING, CA': 'RDD',
  'REDDING, CALIFORNIA': 'RDD',
  
  'FRESNO': 'FAT',
  'FRESNO, USA': 'FAT',
  'FRESNO, CA': 'FAT',
  'FRESNO, CALIFORNIA': 'FAT',
  
  'BAKERSFIELD': 'BFL',
  'BAKERSFIELD, USA': 'BFL',
  'BAKERSFIELD, CA': 'BFL',
  'BAKERSFIELD, CALIFORNIA': 'BFL',
  
  'SANTA BARBARA': 'SBA',
  'SANTA BARBARA, USA': 'SBA',
  'SANTA BARBARA, CA': 'SBA',
  'SANTA BARBARA, CALIFORNIA': 'SBA',
  
  'MONTEREY': 'MRY',
  'MONTEREY, USA': 'MRY',
  'MONTEREY, CA': 'MRY',
  'MONTEREY, CALIFORNIA': 'MRY',
  
  'PALM SPRINGS': 'PSP',
  'PALM SPRINGS, USA': 'PSP',
  'PALM SPRINGS, CA': 'PSP',
  'PALM SPRINGS, CALIFORNIA': 'PSP',
  
  'FLAGSTAFF': 'FLG',
  'FLAGSTAFF, USA': 'FLG',
  'FLAGSTAFF, AZ': 'FLG',
  'FLAGSTAFF, ARIZONA': 'FLG',
  
  'GRAND CANYON': 'GCN',
  'GRAND CANYON, USA': 'GCN',
  'GRAND CANYON NATIONAL PARK': 'GCN',
  
  'SEDONA': 'FLG',
  'SEDONA, USA': 'FLG',
  'SEDONA, AZ': 'FLG',
  
  'SCOTTSDALE': 'PHX',
  'SCOTTSDALE, USA': 'PHX',
  'SCOTTSDALE, AZ': 'PHX',
  
  'MESA': 'PHX',
  'MESA, USA': 'PHX',
  'MESA, AZ': 'PHX',
  
  'CHANDLER': 'PHX',
  'CHANDLER, USA': 'PHX',
  'CHANDLER, AZ': 'PHX',
  
  'GLENDALE': 'PHX',
  'GLENDALE, USA': 'PHX',
  'GLENDALE, AZ': 'PHX',
  
  'TEMPE': 'PHX',
  'TEMPE, USA': 'PHX',
  'TEMPE, AZ': 'PHX',
  
  'GILBERT': 'PHX',
  'GILBERT, USA': 'PHX',
  'GILBERT, AZ': 'PHX',
  
  'PEORIA': 'PHX',
  'PEORIA, USA': 'PHX',
  'PEORIA, AZ': 'PHX',
  
  'SURPRISE': 'PHX',
  'SURPRISE, USA': 'PHX',
  'SURPRISE, AZ': 'PHX',
  
  'AVONDALE': 'PHX',
  'AVONDALE, USA': 'PHX',
  'AVONDALE, AZ': 'PHX',
  
  'GOODYEAR': 'PHX',
  'GOODYEAR, USA': 'PHX',
  'GOODYEAR, AZ': 'PHX',
  
  'BUCKEYE': 'PHX',
  'BUCKEYE, USA': 'PHX',
  'BUCKEYE, AZ': 'PHX',
  
  'EL MIRAGE': 'PHX',
  'EL MIRAGE, USA': 'PHX',
  'EL MIRAGE, AZ': 'PHX',
  
  'YOUNGTOWN': 'PHX',
  'YOUNGTOWN, USA': 'PHX',
  'YOUNGTOWN, AZ': 'PHX',
  
  'SUN CITY': 'PHX',
  'SUN CITY, USA': 'PHX',
  'SUN CITY, AZ': 'PHX',
  
  'SUN CITY WEST': 'PHX',
  'SUN CITY WEST, USA': 'PHX',
  'SUN CITY WEST, AZ': 'PHX',
  
  'FOUNTAIN HILLS': 'PHX',
  'FOUNTAIN HILLS, USA': 'PHX',
  'FOUNTAIN HILLS, AZ': 'PHX',
  
  'PARADISE VALLEY': 'PHX',
  'PARADISE VALLEY, USA': 'PHX',
  'PARADISE VALLEY, AZ': 'PHX',
  
  'CAVE CREEK': 'PHX',
  'CAVE CREEK, USA': 'PHX',
  'CAVE CREEK, AZ': 'PHX',
  
  'CAREFREE': 'PHX',
  'CAREFREE, USA': 'PHX',
  'CAREFREE, AZ': 'PHX',
  
  'NEW RIVER': 'PHX',
  'NEW RIVER, USA': 'PHX',
  'NEW RIVER, AZ': 'PHX',
  
  'ANTHEM': 'PHX',
  'ANTHEM, USA': 'PHX',
  'ANTHEM, AZ': 'PHX',
  
  'DESERT HILLS': 'PHX',
  'DESERT HILLS, USA': 'PHX',
  'DESERT HILLS, AZ': 'PHX',
  
  'BLACK CANYON CITY': 'PHX',
  'BLACK CANYON CITY, USA': 'PHX',
  'BLACK CANYON CITY, AZ': 'PHX',
  
  'CORDES LAKES': 'PRC',
  'CORDES LAKES, USA': 'PRC',
  'CORDES LAKES, AZ': 'PRC',
  
  'MAYER': 'PRC',
  'MAYER, USA': 'PRC',
  'MAYER, AZ': 'PRC',
  
  'DEWEY-HUMBOLDT': 'PRC',
  'DEWEY-HUMBOLDT, USA': 'PRC',
  'DEWEY-HUMBOLDT, AZ': 'PRC',
  
  'PRESCOTT': 'PRC',
  'PRESCOTT, USA': 'PRC',
  'PRESCOTT, AZ': 'PRC',
  'PRESCOTT, ARIZONA': 'PRC',
  
  'PRESCOTT VALLEY': 'PRC',
  'PRESCOTT VALLEY, USA': 'PRC',
  'PRESCOTT VALLEY, AZ': 'PRC',
  
  'CHINO VALLEY': 'PRC',
  'CHINO VALLEY, USA': 'PRC',
  'CHINO VALLEY, AZ': 'PRC',
  
  'CAMP VERDE': 'FLG',
  'CAMP VERDE, USA': 'FLG',
  'CAMP VERDE, AZ': 'FLG',
  
  'COTTONWOOD': 'PRC',
  'COTTONWOOD, USA': 'PRC',
  'COTTONWOOD, AZ': 'PRC',
  
  'CLARKDALE': 'PRC',
  'CLARKDALE, USA': 'PRC',
  'CLARKDALE, AZ': 'PRC',
  
  'JEROME': 'PRC',
  'JEROME, USA': 'PRC',
  'JEROME, AZ': 'PRC',
  
  'OAK CREEK': 'FLG',
  'OAK CREEK, USA': 'FLG',
  'OAK CREEK, AZ': 'FLG',
  
  'VILLAGE OF OAK CREEK': 'FLG',
  'VILLAGE OF OAK CREEK, USA': 'FLG',
  
  'CORNVILLE': 'FLG',
  'CORNVILLE, USA': 'FLG',
  'CORNVILLE, AZ': 'FLG',
  
  'RIMROCK': 'FLG',
  'RIMROCK, USA': 'FLG',
  'RIMROCK, AZ': 'FLG',
  
  'MCGUIREVILLE': 'FLG',
  'MCGUIREVILLE, USA': 'FLG',
  'MCGUIREVILLE, AZ': 'FLG',
  
  'LAKE MONTEZUMA': 'FLG',
  'LAKE MONTEZUMA, USA': 'FLG',
  'LAKE MONTEZUMA, AZ': 'FLG',
  
  'RINCON': 'TUS',
  'RINCON, USA': 'TUS',
  'RINCON, AZ': 'TUS',
  
  'PAYSON': 'PHX',
  'PAYSON, USA': 'PHX',
  'PAYSON, AZ': 'PHX',
  
  'PINE': 'PHX',
  'PINE, USA': 'PHX',
  'PINE, AZ': 'PHX',
  
  'STRAWBERRY': 'PHX',
  'STRAWBERRY, USA': 'PHX',
  'STRAWBERRY, AZ': 'PHX',
  
  'YOUNG': 'PHX',
  'YOUNG, USA': 'PHX',
  'YOUNG, AZ': 'PHX',
  
  'CHRISTOPHER CREEK': 'PHX',
  'CHRISTOPHER CREEK, USA': 'PHX',
  'CHRISTOPHER CREEK, AZ': 'PHX',
  
  'HEBER-OVERGAARD': 'FLG',
  'HEBER-OVERGAARD, USA': 'FLG',
  'HEBER-OVERGAARD, AZ': 'FLG',
  
  'PINETOP-LAKESIDE': 'PHX',
  'PINETOP-LAKESIDE, USA': 'PHX',
  'PINETOP-LAKESIDE, AZ': 'PHX',
  
  'SHOW LOW': 'PHX',
  'SHOW LOW, USA': 'PHX',
  'SHOW LOW, AZ': 'PHX',
  
  'SNOWFLAKE': 'PHX',
  'SNOWFLAKE, USA': 'PHX',
  'SNOWFLAKE, AZ': 'PHX',
  
  'TAYLOR': 'PHX',
  'TAYLOR, USA': 'PHX',
  'TAYLOR, AZ': 'PHX',
  
  'WINSLOW': 'FLG',
  'WINSLOW, USA': 'FLG',
  'WINSLOW, AZ': 'FLG',
  
  'HOLBROOK': 'FLG',
  'HOLBROOK, USA': 'FLG',
  'HOLBROOK, AZ': 'FLG',
  
  'JOSEPH CITY': 'FLG',
  'JOSEPH CITY, USA': 'FLG',
  'JOSEPH CITY, AZ': 'FLG',
  
  'SUN VALLEY': 'SUN',
  'SUN VALLEY, USA': 'SUN',
  'SUN VALLEY, ID': 'SUN',
  'SUN VALLEY, IDAHO': 'SUN',
  
  'NAVAJO': 'FLG',
  'NAVAJO, USA': 'FLG',
  'NAVAJO, AZ': 'FLG',
  
  'CHAMBERS': 'FLG',
  'CHAMBERS, USA': 'FLG',
  'CHAMBERS, AZ': 'FLG',
  
  'LUPTON': 'FLG',
  'LUPTON, USA': 'FLG',
  'LUPTON, AZ': 'FLG',
  
  'SANDERS': 'FLG',
  'SANDERS, USA': 'FLG',
  'SANDERS, AZ': 'FLG',
  
  'HOUCK': 'FLG',
  'HOUCK, USA': 'FLG',
  'HOUCK, AZ': 'FLG',
  
  'ST. JOHNS': 'PHX',
  'ST JOHNS': 'PHX',
  'ST. JOHNS, USA': 'PHX',
  'ST JOHNS, USA': 'PHX',
  'ST. JOHNS, AZ': 'PHX',
  
  'SPRINGERVILLE': 'PHX',
  'SPRINGERVILLE, USA': 'PHX',
  'SPRINGERVILLE, AZ': 'PHX',
  
  'EAGAR': 'PHX',
  'EAGAR, USA': 'PHX',
  'EAGAR, AZ': 'PHX',
  
  'NUTRIOSO': 'PHX',
  'NUTRIOSO, USA': 'PHX',
  'NUTRIOSO, AZ': 'PHX',
  
  'ALPINE': 'PHX',
  'ALPINE, USA': 'PHX',
  'ALPINE, AZ': 'PHX',
  
  'GREER': 'PHX',
  'GREER, USA': 'PHX',
  'GREER, AZ': 'PHX',
  
  'MCNARY': 'PHX',
  'MCNARY, USA': 'PHX',
  'MCNARY, AZ': 'PHX',
  
  'FORT APACHE': 'PHX',
  'FORT APACHE, USA': 'PHX',
  'FORT APACHE, AZ': 'PHX',
  
  'WHITERIVER': 'PHX',
  'WHITERIVER, USA': 'PHX',
  'WHITERIVER, AZ': 'PHX',
  
  'CIBECUE': 'PHX',
  'CIBECUE, USA': 'PHX',
  'CIBECUE, AZ': 'PHX',
  
  'CARRIZO': 'PHX',
  'CARRIZO, USA': 'PHX',
  'CARRIZO, AZ': 'PHX',
  
  'HON-DAH': 'PHX',
  'HON-DAH, USA': 'PHX',
  'HON-DAH, AZ': 'PHX',
  
  'PINETOP': 'PHX',
  'PINETOP, USA': 'PHX',
  'PINETOP, AZ': 'PHX',
  
  'LAKESIDE': 'PHX',
  'LAKESIDE, USA': 'PHX',
  'LAKESIDE, AZ': 'PHX',
  
  'VERNON': 'PHX',
  'VERNON, USA': 'PHX',
  'VERNON, AZ': 'PHX',
  
  'CONCHO': 'PHX',
  'CONCHO, USA': 'PHX',
  'CONCHO, AZ': 'PHX',

  // ===========================================
  // 🇨🇦 Canada - Principal Airports
  // ===========================================
  'TORONTO': 'YYZ',
  'TORONTO, CANADA': 'YYZ',
  'TORONTO, CA': 'YYZ',
  'CANADA': 'YYZ',
  
  'VANCOUVER': 'YVR',
  'VANCOUVER, CANADA': 'YVR',
  'VANCOUVER, CA': 'YVR',
  
  'MONTREAL': 'YUL',
  'MONTREAL, CANADA': 'YUL',
  'MONTREAL, CA': 'YUL',
  
  'CALGARY': 'YYC',
  'CALGARY, CANADA': 'YYC',
  'CALGARY, CA': 'YYC',
  
  'EDMONTON': 'YEG',
  'EDMONTON, CANADA': 'YEG',
  'EDMONTON, CA': 'YEG',
  
  'OTTAWA': 'YOW',
  'OTTAWA, CANADA': 'YOW',
  'OTTAWA, CA': 'YOW',
  
  'WINNIPEG': 'YWG',
  'WINNIPEG, CANADA': 'YWG',
  'WINNIPEG, CA': 'YWG',
  
  'QUEBEC CITY': 'YQB',
  'QUEBEC CITY, CANADA': 'YQB',
  'QUEBEC CITY, CA': 'YQB',
  
  'HAMILTON': 'YHM',
  'HAMILTON, CANADA': 'YHM',
  'HAMILTON, CA': 'YHM',
  
  'KITCHENER': 'YKF',
  'KITCHENER, CANADA': 'YKF',
  'KITCHENER, CA': 'YKF',
  
  'LONDON': 'YXU',
  'LONDON, CANADA': 'YXU',
  'LONDON, CA': 'YXU',
  
  'VICTORIA': 'YYJ',
  'VICTORIA, CANADA': 'YYJ',
  'VICTORIA, CA': 'YYJ',
  
  'HALIFAX': 'YHZ',
  'HALIFAX, CANADA': 'YHZ',
  'HALIFAX, CA': 'YHZ',
  
  'OSHAWA': 'YOO',
  'OSHAWA, CANADA': 'YOO',
  
  'WINDSOR': 'YQG',
  'WINDSOR, CANADA': 'YQG',
  
  'SASKATOON': 'YXE',
  'SASKATOON, CANADA': 'YXE',
  
  'REGINA': 'YQR',
  'REGINA, CANADA': 'YQR',
  
  'ST. JOHN\'S': 'YYT',
  'ST JOHNS': 'YYT',
  'ST. JOHN\'S, CANADA': 'YYT',
  
  'BARRIE': 'YBR',
  'BARRIE, CANADA': 'YBR',
  
  'KELOWNA': 'YLW',
  'KELOWNA, CANADA': 'YLW',
  
  'ABBOTSFORD': 'YXX',
  'ABBOTSFORD, CANADA': 'YXX',
  
  'KINGSTON': 'YGK',
  'KINGSTON, CANADA': 'YGK',
  
  'SUDBURY': 'YSB',
  'SUDBURY, CANADA': 'YSB',
  
  'SHERBROOKE': 'YSC',
  'SHERBROOKE, CANADA': 'YSC',
  
  'SAGUENAY': 'YBG',
  'SAGUENAY, CANADA': 'YBG',
  
  'LEVIS': 'YQB',
  'LÉVIS, CANADA': 'YQB',
  
  'TROIS-RIVIÈRES': 'YRQ',
  'TROIS-RIVIERES': 'YRQ',
  'TROIS-RIVIÈRES, CANADA': 'YRQ',
  
  'TERREBONNE': 'YUL',
  'TERREBONNE, CANADA': 'YUL',
  
  'SAINT-JEAN-SUR-RICHELIEU': 'YUL',
  'SAINT-JEAN-SUR-RICHELIEU, CANADA': 'YUL',
  
  'REPENTIGNY': 'YUL',
  'REPENTIGNY, CANADA': 'YUL',
  
  'BROSSARD': 'YUL',
  'BROSSARD, CANADA': 'YUL',
  
  'DRUMMONDVILLE': 'YUL',
  'DRUMMONDVILLE, CANADA': 'YUL',
  
  'SAINT-JÉRÔME': 'YUL',
  'SAINT-JEROME': 'YUL',
  'SAINT-JÉRÔME, CANADA': 'YUL',
  
  'GRANBY': 'YUL',
  'GRANBY, CANADA': 'YUL',
  
  'BLAINVILLE': 'YUL',
  'BLAINVILLE, CANADA': 'YUL',
  
  'SAINT-HYACINTHE': 'YUL',
  'SAINT-HYACINTHE, CANADA': 'YUL',
  
  'SHAWINIGAN': 'YQC',
  'SHAWINIGAN, CANADA': 'YQC',
  
  'DOLLARD-DES-ORMEAUX': 'YUL',
  'DOLLARD-DES-ORMEAUX, CANADA': 'YUL',
  
  'BRANDON': 'YBR',
  'BRANDON, CANADA': 'YBR',
  
  'RED DEER': 'YQF',
  'RED DEER, CANADA': 'YQF',
  
  'LETHBRIDGE': 'YQL',
  'LETHBRIDGE, CANADA': 'YQL',
  
  'KAMLOOPS': 'YKA',
  'KAMLOOPS, CANADA': 'YKA',
  
  'NANAIMO': 'YCD',
  'NANAIMO, CANADA': 'YCD',
  
  'PRINCE GEORGE': 'YXS',
  'PRINCE GEORGE, CANADA': 'YXS',
  
  'CHILLIWACK': 'YCW',
  'CHILLIWACK, CANADA': 'YCW',
  
  'VERNON': 'YVE',
  'VERNON, CANADA': 'YVE',
  
  'PENTICTON': 'YYF',
  'PENTICTON, CANADA': 'YYF',
  
  'CAMPBELL RIVER': 'YBL',
  'CAMPBELL RIVER, CANADA': 'YBL',
  
  'COURTENAY': 'YCA',
  'COURTENAY, CANADA': 'YCA',
  
  'CRANBROOK': 'YXC',
  'CRANBROOK, CANADA': 'YXC',
  
  'FORT ST. JOHN': 'YXJ',
  'FORT ST JOHN': 'YXJ',
  'FORT ST. JOHN, CANADA': 'YXJ',
  
  'DAWSON CREEK': 'YDQ',
  'DAWSON CREEK, CANADA': 'YDQ',
  
  'TERRACE': 'YXT',
  'TERRACE, CANADA': 'YXT',
  
  'PRINCE RUPERT': 'YPR',
  'PRINCE RUPERT, CANADA': 'YPR',
  
  'WHITEHORSE': 'YXY',
  'WHITEHORSE, CANADA': 'YXY',
  
  'YELLOWKNIFE': 'YZF',
  'YELLOWKNIFE, CANADA': 'YZF',
  
  'IQALUIT': 'YFB',
  'IQALUIT, CANADA': 'YFB',

  // ===========================================
  // 🇪🇺 Europa - Principal Airports
  // ===========================================
  'LONDON': 'LHR',
  'LONDON, UK': 'LHR',
  'LONDON, UNITED KINGDOM': 'LHR',
  'LONDON, ENGLAND': 'LHR',
  'GREAT BRITAIN': 'LHR',
  'UK': 'LHR',
  
  'PARIS': 'CDG',
  'PARIS, FRANCE': 'CDG',
  'PARIS, FR': 'CDG',
  
  'ROME': 'FCO',
  'ROME, ITALY': 'FCO',
  'ROME, IT': 'FCO',
  'ROMA': 'FCO',
  
  'BARCELONA': 'BCN',
  'BARCELONA, SPAIN': 'BCN',
  'BARCELONA, ES': 'BCN',
  
  'MADRID': 'MAD',
  'MADRID, SPAIN': 'MAD',
  'MADRID, ES': 'MAD',
  
  'AMSTERDAM': 'AMS',
  'AMSTERDAM, NETHERLANDS': 'AMS',
  'AMSTERDAM, NL': 'AMS',
  'NETHERLANDS': 'AMS',
  
  'FRANKFURT': 'FRA',
  'FRANKFURT, GERMANY': 'FRA',
  'FRANKFURT, DE': 'FRA',
  'GERMANY': 'FRA',
  
  'ZURICH': 'ZRH',
  'ZURICH, SWITZERLAND': 'ZRH',
  'ZURICH, CH': 'ZRH',
  'SWITZERLAND': 'ZRH',
  
  'ISTANBUL': 'IST',
  'ISTANBUL, TURKEY': 'IST',
  'ISTANBUL, TR': 'IST',
  'TURKEY': 'IST',
  
  'LISBON': 'LIS',
  'LISBON, PORTUGAL': 'LIS',
  'LISBON, PT': 'LIS',
  
  'DUBLIN': 'DUB',
  'DUBLIN, IRELAND': 'DUB',
  'DUBLIN, IE': 'DUB',
  
  'EDINBURGH': 'EDI',
  'EDINBURGH, UK': 'EDI',
  'EDINBURGH, SCOTLAND': 'EDI',
  
  'MANCHESTER': 'MAN',
  'MANCHESTER, UK': 'MAN',
  'MANCHESTER, ENGLAND': 'MAN',
  
  'MUNICH': 'MUC',
  'MUNICH, GERMANY': 'MUC',
  'MUNICH, DE': 'MUC',
  
  'BERLIN': 'BER',
  'BERLIN, GERMANY': 'BER',
  'BERLIN, DE': 'BER',
  
  'VIENNA': 'VIE',
  'VIENNA, AUSTRIA': 'VIE',
  'VIENNA, AT': 'VIE',
  
  'PRAGUE': 'PRG',
  'PRAGUE, CZECH REPUBLIC': 'PRG',
  'PRAGUE, CZ': 'PRG',
  
  'WARSAW': 'WAW',
  'WARSAW, POLAND': 'WAW',
  'WARSAW, PL': 'WAW',
  
  'BRUSSELS': 'BRU',
  'BRUSSELS, BELGIUM': 'BRU',
  'BRUSSELS, BE': 'BRU',
  
  'COPENHAGEN': 'CPH',
  'COPENHAGEN, DENMARK': 'CPH',
  'COPENHAGEN, DK': 'CPH',
  
  'STOCKHOLM': 'ARN',
  'STOCKHOLM, SWEDEN': 'ARN',
  'STOCKHOLM, SE': 'ARN',
  
  'OSLO': 'OSL',
  'OSLO, NORWAY': 'OSL',
  'OSLO, NO': 'OSL',
  
  'HELSINKI': 'HEL',
  'HELSINKI, FINLAND': 'HEL',
  'HELSINKI, FI': 'HEL',
  
  'ATHENS': 'ATH',
  'ATHENS, GREECE': 'ATH',
  'ATHENS, GR': 'ATH',
  
  'BUDAPEST': 'BUD',
  'BUDAPEST, HUNGARY': 'BUD',
  'BUDAPEST, HU': 'BUD',
  
  'BUCHAREST': 'OTP',
  'BUCHAREST, ROMANIA': 'OTP',
  'BUCHAREST, RO': 'OTP',
  
  'SOFIA': 'SOF',
  'SOFIA, BULGARIA': 'SOF',
  'SOFIA, BG': 'SOF',
  
  'ZAGREB': 'ZAG',
  'ZAGREB, CROATIA': 'ZAG',
  'ZAGREB, HR': 'ZAG',
  
  'LJUBLJANA': 'LJU',
  'LJUBLJANA, SLOVENIA': 'LJU',
  'LJUBLJANA, SI': 'LJU',
  
  'BRATISLAVA': 'BTS',
  'BRATISLAVA, SLOVAKIA': 'BTS',
  'BRATISLAVA, SK': 'BTS',
  
  'TALLINN': 'TLL',
  'TALLINN, ESTONIA': 'TLL',
  'TALLINN, EE': 'TLL',
  
  'RIGA': 'RIX',
  'RIGA, LATVIA': 'RIX',
  'RIGA, LV': 'RIX',
  
  'VILNIUS': 'VNO',
  'VILNIUS, LITHUANIA': 'VNO',
  'VILNIUS, LT': 'VNO',
  
  'REYKJAVIK': 'KEF',
  'REYKJAVIK, ICELAND': 'KEF',
  'REYKJAVIK, IS': 'KEF',
  'ICELAND': 'KEF',
  
  'LUXEMBOURG': 'LUX',
  'LUXEMBOURG, LUXEMBOURG': 'LUX',
  'LUXEMBOURG, LU': 'LUX',
  
  'VALLETTA': 'MLA',
  'VALLETTA, MALTA': 'MLA',
  'MALTA': 'MLA',
  
  'NICOSIA': 'LCA',
  'NICOSIA, CYPRUS': 'LCA',
  'CYPRUS': 'LCA',
  
  'MONACO': 'NCE',
  'MONACO, MONACO': 'NCE',
  
  'SAN MARINO': 'RMI',
  'SAN MARINO, SAN MARINO': 'RMI',
  
  'VATICAN CITY': 'FCO',
  'VATICAN CITY, VATICAN CITY': 'FCO',
  
  'ANDORRA LA VELLA': 'BCN',
  'ANDORRA LA VELLA, ANDORRA': 'BCN',
  
  'LIECHTENSTEIN': 'ZRH',
  'LIECHTENSTEIN, LIECHTENSTEIN': 'ZRH',
  
  'GIBRALTAR': 'GIB',
  'GIBRALTAR, GIBRALTAR': 'GIB',
  
  'BELFAST': 'BFS',
  'BELFAST, UK': 'BFS',
  'BELFAST, NORTHERN IRELAND': 'BFS',
  
  'CARDIFF': 'CWL',
  'CARDIFF, UK': 'CWL',
  'CARDIFF, WALES': 'CWL',
  
  'GLASGOW': 'GLA',
  'GLASGOW, UK': 'GLA',
  'GLASGOW, SCOTLAND': 'GLA',
  
  'LIVERPOOL': 'LPL',
  'LIVERPOOL, UK': 'LPL',
  'LIVERPOOL, ENGLAND': 'LPL',
  
  'NEWCASTLE': 'NCL',
  'NEWCASTLE, UK': 'NCL',
  'NEWCASTLE, ENGLAND': 'NCL',
  
  'LEEDS': 'LBA',
  'LEEDS, UK': 'LBA',
  'LEEDS, ENGLAND': 'LBA',
  
  'SHEFFIELD': 'MAN',
  'SHEFFIELD, UK': 'MAN',
  'SHEFFIELD, ENGLAND': 'MAN',
  
  'NOTTINGHAM': 'EMA',
  'NOTTINGHAM, UK': 'EMA',
  'NOTTINGHAM, ENGLAND': 'EMA',
  
  'LEICESTER': 'EMA',
  'LEICESTER, UK': 'EMA',
  'LEICESTER, ENGLAND': 'EMA',
  
  'COVENTRY': 'BHX',
  'COVENTRY, UK': 'BHX',
  'COVENTRY, ENGLAND': 'BHX',
  
  'BRADFORD': 'LBA',
  'BRADFORD, UK': 'LBA',
  'BRADFORD, ENGLAND': 'LBA',
  
  'STOKE-ON-TRENT': 'MAN',
  'STOKE-ON-TRENT, UK': 'MAN',
  
  'WOLVERHAMPTON': 'BHX',
  'WOLVERHAMPTON, UK': 'BHX',
  
  'PLYMOUTH': 'PLH',
  'PLYMOUTH, UK': 'PLH',
  
  'SOUTHAMPTON': 'SOU',
  'SOUTHAMPTON, UK': 'SOU',
  
  'READING': 'LHR',
  'READING, UK': 'LHR',
  
  'DERBY': 'EMA',
  'DERBY, UK': 'EMA',
  
  'PORTSMOUTH': 'SOU',
  'PORTSMOUTH, UK': 'SOU',
  
  'YORK': 'LBA',
  'YORK, UK': 'LBA',
  
  'PETERBOROUGH': 'STN',
  'PETERBOROUGH, UK': 'STN',
  
  'CAMBRIDGE': 'STN',
  'CAMBRIDGE, UK': 'STN',
  
  'OXFORD': 'LHR',
  'OXFORD, UK': 'LHR',
  
  'BRIGHTON': 'LGW',
  'BRIGHTON, UK': 'LGW',
  
  'BOURNEMOUTH': 'BOH',
  'BOURNEMOUTH, UK': 'BOH',
  
  'SWINDON': 'LHR',
  'SWINDON, UK': 'LHR',
  
  'NORTHAMPTON': 'BHX',
  'NORTHAMPTON, UK': 'BHX',
  
  'NORWICH': 'NWI',
  'NORWICH, UK': 'NWI',
  
  'LUTON': 'LTN',
  'LUTON, UK': 'LTN',
  
  'MILTON KEYNES': 'LHR',
  'MILTON KEYNES, UK': 'LHR',
  
  'SLOUGH': 'LHR',
  'SLOUGH, UK': 'LHR',
  
  'GLOUCESTER': 'BHX',
  'GLOUCESTER, UK': 'BHX',
  
  'EXETER': 'EXT',
  'EXETER, UK': 'EXT',
  
  'BATH': 'BRS',
  'BATH, UK': 'BRS',
  
  'CHESTER': 'MAN',
  'CHESTER, UK': 'MAN',
  
  'CANTERBURY': 'LGW',
  'CANTERBURY, UK': 'LGW',
  
  'SALISBURY': 'SOU',
  'SALISBURY, UK': 'SOU',
  
  'WINCHESTER': 'SOU',
  'WINCHESTER, UK': 'SOU',
  
  'CHICHESTER': 'LGW',
  'CHICHESTER, UK': 'LGW',
  
  'WELLS': 'BRS',
  'WELLS, UK': 'BRS',
  
  'TRURO': 'NQY',
  'TRURO, UK': 'NQY',
  
  'ST. DAVIDS': 'CWL',
  'ST. DAVIDS, UK': 'CWL',
  
  'BANGOR': 'LPL',
  'BANGOR, UK': 'LPL',
  
  'ARMAGH': 'BFS',
  'ARMAGH, UK': 'BFS',
  
  'LONDONDERRY': 'LDY',
  'LONDONDERRY, UK': 'LDY',
  
  'LYON': 'LYS',
  'LYON, FRANCE': 'LYS',
  'LYON, FR': 'LYS',
  
  'MARSEILLE': 'MRS',
  'MARSEILLE, FRANCE': 'MRS',
  'MARSEILLE, FR': 'MRS',
  
  'TOULOUSE': 'TLS',
  'TOULOUSE, FRANCE': 'TLS',
  'TOULOUSE, FR': 'TLS',
  
  'NICE': 'NCE',
  'NICE, FRANCE': 'NCE',
  'NICE, FR': 'NCE',
  
  'NANTES': 'NTE',
  'NANTES, FRANCE': 'NTE',
  'NANTES, FR': 'NTE',
  
  'STRASBOURG': 'SXB',
  'STRASBOURG, FRANCE': 'SXB',
  'STRASBOURG, FR': 'SXB',
  
  'MONTPELLIER': 'MPL',
  'MONTPELLIER, FRANCE': 'MPL',
  'MONTPELLIER, FR': 'MPL',
  
  'BORDEAUX': 'BOD',
  'BORDEAUX, FRANCE': 'BOD',
  'BORDEAUX, FR': 'BOD',
  
  'LILLE': 'LIL',
  'LILLE, FRANCE': 'LIL',
  'LILLE, FR': 'LIL',
  
  'RENNES': 'RNS',
  'RENNES, FRANCE': 'RNS',
  'RENNES, FR': 'RNS',
  
  'REIMS': 'RHE',
  'REIMS, FRANCE': 'RHE',
  'REIMS, FR': 'RHE',
  
  'LE HAVRE': 'LEH',
  'LE HAVRE, FRANCE': 'LEH',
  'LE HAVRE, FR': 'LEH',
  
  'SAINT-ÉTIENNE': 'EBU',
  'SAINT-ETIENNE': 'EBU',
  'SAINT-ÉTIENNE, FRANCE': 'EBU',
  
  'TOULON': 'TLN',
  'TOULON, FRANCE': 'TLN',
  'TOULON, FR': 'TLN',
  
  'GRENOBLE': 'GNB',
  'GRENOBLE, FRANCE': 'GNB',
  'GRENOBLE, FR': 'GNB',
  
  'DIJON': 'DIJ',
  'DIJON, FRANCE': 'DIJ',
  'DIJON, FR': 'DIJ',
  
  'ANGERS': 'ANE',
  'ANGERS, FRANCE': 'ANE',
  
  'NÎMES': 'FNI',
  'NIMES': 'FNI',
  'NÎMES, FRANCE': 'FNI',
  
  'VILLEURBANNE': 'LYS',
  'VILLEURBANNE, FRANCE': 'LYS',
  
  'LE MANS': 'LME',
  'LE MANS, FRANCE': 'LME',
  
  'AIX-EN-PROVENCE': 'MRS',
  'AIX-EN-PROVENCE, FRANCE': 'MRS',
  
  'CLERMONT-FERRAND': 'CFE',
  'CLERMONT-FERRAND, FRANCE': 'CFE',
  
  'BREST': 'BES',
  'BREST, FRANCE': 'BES',
  
  'TOURS': 'TUF',
  'TOURS, FRANCE': 'TUF',
  
  'AMIENS': 'BVA',
  'AMIENS, FRANCE': 'BVA',
  
  'LIMOGES': 'LIG',
  'LIMOGES, FRANCE': 'LIG',
  
  'ANNECY': 'GVA',
  'ANNECY, FRANCE': 'GVA',
  
  'PERPIGNAN': 'PGF',
  'PERPIGNAN, FRANCE': 'PGF',
  
  'BOULOGNE-BILLANCOURT': 'ORY',
  'BOULOGNE-BILLANCOURT, FRANCE': 'ORY',
  
  'METZ': 'ETZ',
  'METZ, FRANCE': 'ETZ',
  
  'BESANÇON': 'BSL',
  'BESANCON': 'BSL',
  'BESANÇON, FRANCE': 'BSL',
  
  'ORLÉANS': 'ORY',
  'ORLEANS': 'ORY',
  'ORLÉANS, FRANCE': 'ORY',
  
  'MULHOUSE': 'BSL',
  'MULHOUSE, FRANCE': 'BSL',
  
  'ROUEN': 'URO',
  'ROUEN, FRANCE': 'URO',
  
  'CAEN': 'CFR',
  'CAEN, FRANCE': 'CFR',
  
  'NANCY': 'ETZ',
  'NANCY, FRANCE': 'ETZ',
  
  'ARGENTEUIL': 'CDG',
  'ARGENTEUIL, FRANCE': 'CDG',
  
  'MONTREUIL': 'CDG',
  'MONTREUIL, FRANCE': 'CDG',
  
  'SAINT-DENIS': 'CDG',
  'SAINT-DENIS, FRANCE': 'CDG',
  
  'ROUBAIX': 'LIL',
  'ROUBAIX, FRANCE': 'LIL',
  
  'TOURCOING': 'LIL',
  'TOURCOING, FRANCE': 'LIL',
  
  'NANTERRE': 'CDG',
  'NANTERRE, FRANCE': 'CDG',
  
  'AVIGNON': 'AVN',
  'AVIGNON, FRANCE': 'AVN',
  
  'CRÉTEIL': 'ORY',
  'CRETEIL': 'ORY',
  'CRÉTEIL, FRANCE': 'ORY',
  
  'DUNKERQUE': 'LIL',
  'DUNKERQUE, FRANCE': 'LIL',
  
  'POITIERS': 'PIS',
  'POITIERS, FRANCE': 'PIS',
  
  'AULNAY-SOUS-BOIS': 'CDG',
  'AULNAY-SOUS-BOIS, FRANCE': 'CDG',
  
  'SAINT-PIERRE': 'RUN',
  'SAINT-PIERRE, FRANCE': 'RUN',
  
  'RUEIL-MALMAISON': 'ORY',
  'RUEIL-MALMAISON, FRANCE': 'ORY',
  
  'PAU': 'PUF',
  'PAU, FRANCE': 'PUF',
  
  'AUBERVILLIERS': 'CDG',
  'AUBERVILLIERS, FRANCE': 'CDG',
  
  'LE TAMPON': 'RUN',
  'LE TAMPON, FRANCE': 'RUN',
  
  'CHAMPIGNY-SUR-MARNE': 'ORY',
  'CHAMPIGNY-SUR-MARNE, FRANCE': 'ORY',
  
  'ANTIBES': 'NCE',
  'ANTIBES, FRANCE': 'NCE',
  
  'LA ROCHELLE': 'LRH',
  'LA ROCHELLE, FRANCE': 'LRH',
  
  'CANNES': 'CEQ',
  'CANNES, FRANCE': 'CEQ',
  
  'CALAIS': 'CQF',
  'CALAIS, FRANCE': 'CQF',
  
  'SAINT-MAUR-DES-FOSSÉS': 'ORY',
  'SAINT-MAUR-DES-FOSSES': 'ORY',
  'SAINT-MAUR-DES-FOSSÉS, FRANCE': 'ORY',
  
  'BOURGES': 'BOU',
  'BOURGES, FRANCE': 'BOU',
  
  'DRANCY': 'CDG',
  'DRANCY, FRANCE': 'CDG',
  
  'AJACCIO': 'AJA',
  'AJACCIO, FRANCE': 'AJA',
  
  'COLMAR': 'EAP',
  'COLMAR, FRANCE': 'EAP',
  
  'MÉRIGNAC': 'BOD',
  'MERIGNAC': 'BOD',
  'MÉRIGNAC, FRANCE': 'BOD',
  
  'SAINT-NAZAIRE': 'NTE',
  'SAINT-NAZAIRE, FRANCE': 'NTE',
  
  'VALENCE': 'VAF',
  'VALENCE, FRANCE': 'VAF',
  
  'ISSY-LES-MOULINEAUX': 'ORY',
  'ISSY-LES-MOULINEAUX, FRANCE': 'ORY',
  
  'LEVALLOIS-PERRET': 'CDG',
  'LEVALLOIS-PERRET, FRANCE': 'CDG',
  
  'QUIMPER': 'UIP',
  'QUIMPER, FRANCE': 'UIP',
  
  'LA SEYNE-SUR-MER': 'TLN',
  'LA SEYNE-SUR-MER, FRANCE': 'TLN',
  
  'ANTONY': 'ORY',
  'ANTONY, FRANCE': 'ORY',
  
  'TROYES': 'QYR',
  'TROYES, FRANCE': 'QYR',
  
  'NEUILLY-SUR-SEINE': 'CDG',
  'NEUILLY-SUR-SEINE, FRANCE': 'CDG',
  
  'SARCELLES': 'CDG',
  'SARCELLES, FRANCE': 'CDG',
  
  'LES ABYMES': 'PTP',
  'LES ABYMES, FRANCE': 'PTP',
  
  'VÉNISSIEUX': 'LYS',
  'VENISSIEUX': 'LYS',
  'VÉNISSIEUX, FRANCE': 'LYS',
  
  'CLICHY': 'CDG',
  'CLICHY, FRANCE': 'CDG',
  
  'LORIENT': 'LRT',
  'LORIENT, FRANCE': 'LRT',
  
  'PESSAC': 'BOD',
  'PESSAC, FRANCE': 'BOD',
  
  'IVRY-SUR-SEINE': 'ORY',
  'IVRY-SUR-SEINE, FRANCE': 'ORY',
  
  'CERGY': 'CDG',
  'CERGY, FRANCE': 'CDG',
  
  'CAYENNE': 'CAY',
  'CAYENNE, FRANCE': 'CAY',
  
  'NIORT': 'NIT',
  'NIORT, FRANCE': 'NIT',
  
  'CHAMBÉRY': 'CMF',
  'CHAMBERY': 'CMF',
  'CHAMBÉRY, FRANCE': 'CMF',
  
  'MONTAUBAN': 'TLS',
  'MONTAUBAN, FRANCE': 'TLS',
  
  'SAINT-QUENTIN': 'SFX',
  'SAINT-QUENTIN, FRANCE': 'SFX',
  
  'VILLEJUIF': 'ORY',
  'VILLEJUIF, FRANCE': 'ORY',
  
  'HYÈRES': 'TLN',
  'HYERES': 'TLN',
  'HYÈRES, FRANCE': 'TLN',
  
  'BEAUVAIS': 'BVA',
  'BEAUVAIS, FRANCE': 'BVA',
  
  'CHOLET': 'NTE',
  'CHOLET, FRANCE': 'NTE',
  
  'VANNES': 'VNE',
  'VANNES, FRANCE': 'VNE',
  
  'LA ROCHE-SUR-YON': 'EDM',
  'LA ROCHE-SUR-YON, FRANCE': 'EDM',
  
  'ÉVRY': 'ORY',
  'EVRY': 'ORY',
  'ÉVRY, FRANCE': 'ORY',
  
  'ARLES': 'MRS',
  'ARLES, FRANCE': 'MRS',
  
  'NARBONNE': 'BZR',
  'NARBONNE, FRANCE': 'BZR',
  
  'GRASSE': 'NCE',
  'GRASSE, FRANCE': 'NCE',
  
  'CHÂLONS-EN-CHAMPAGNE': 'XCR',
  'CHALONS-EN-CHAMPAGNE': 'XCR',
  'CHÂLONS-EN-CHAMPAGNE, FRANCE': 'XCR',
  
  'LE LAMENTIN': 'FDF',
  'LE LAMENTIN, FRANCE': 'FDF',
  
  'NOISY-LE-GRAND': 'CDG',
  'NOISY-LE-GRAND, FRANCE': 'CDG',

  // ===========================================
  // 🌏 Asia - Principal Airports
  // ===========================================
  'TOKYO': 'NRT',
  'TOKYO, JAPAN': 'NRT',
  'TOKYO, JP': 'NRT',
  'JAPAN': 'NRT',
  'TOKYO NARITA': 'NRT',
  'NARITA': 'NRT',
  
  'OSAKA': 'KIX',
  'OSAKA, JAPAN': 'KIX',
  'OSAKA, JP': 'KIX',
  'KANSAI': 'KIX',
  
  'KYOTO': 'KIX',
  'KYOTO, JAPAN': 'KIX',
  
  'SINGAPORE': 'SIN',
  'SINGAPORE, SINGAPORE': 'SIN',
  'SINGAPORE, SG': 'SIN',
  
  'BANGKOK': 'BKK',
  'BANGKOK, THAILAND': 'BKK',
  'BANGKOK, TH': 'BKK',
  'THAILAND': 'BKK',
  
  'PHUKET': 'HKT',
  'PHUKET, THAILAND': 'HKT',
  'PHUKET, TH': 'HKT',
  
  'CHIANG MAI': 'CNX',
  'CHIANG MAI, THAILAND': 'CNX',
  
  'HONG KONG': 'HKG',
  'HONG KONG, CHINA': 'HKG',
  'HONG KONG, CN': 'HKG',
  'HK': 'HKG',
  
  'SEOUL': 'ICN',
  'SEOUL, SOUTH KOREA': 'ICN',
  'SEOUL, KR': 'ICN',
  'SOUTH KOREA': 'ICN',
  'KOREA': 'ICN',
  
  'BUSAN': 'PUS',
  'BUSAN, SOUTH KOREA': 'PUS',
  
  'SHANGHAI': 'PVG',
  'SHANGHAI, CHINA': 'PVG',
  'SHANGHAI, CN': 'PVG',
  'PUDONG': 'PVG',
  
  'BEIJING': 'PEK',
  'BEIJING, CHINA': 'PEK',
  'BEIJING, CN': 'PEK',
  'CHINA': 'PEK',
  
  'GUANGZHOU': 'CAN',
  'GUANGZHOU, CHINA': 'CAN',
  'GUANGZHOU, CN': 'CAN',
  
  'SHENZHEN': 'SZX',
  'SHENZHEN, CHINA': 'SZX',
  'SHENZHEN, CN': 'SZX',
  
  'CHENGDU': 'CTU',
  'CHENGDU, CHINA': 'CTU',
  'CHENGDU, CN': 'CTU',
  
  'TAIPEI': 'TPE',
  'TAIPEI, TAIWAN': 'TPE',
  'TAIPEI, TW': 'TPE',
  'TAIWAN': 'TPE',
  
  'KUALA LUMPUR': 'KUL',
  'KUALA LUMPUR, MALAYSIA': 'KUL',
  'KUALA LUMPUR, MY': 'KUL',
  'MALAYSIA': 'KUL',
  
  'JAKARTA': 'CGK',
  'JAKARTA, INDONESIA': 'CGK',
  'JAKARTA, ID': 'CGK',
  'INDONESIA': 'CGK',
  
  'BALI': 'DPS',
  'BALI, INDONESIA': 'DPS',
  'DENPASAR': 'DPS',
  
  'MANILA': 'MNL',
  'MANILA, PHILIPPINES': 'MNL',
  'MANILA, PH': 'MNL',
  'PHILIPPINES': 'MNL',
  
  'CEBU': 'CEB',
  'CEBU, PHILIPPINES': 'CEB',
  
  'HANOI': 'HAN',
  'HANOI, VIETNAM': 'HAN',
  'HANOI, VN': 'HAN',
  'VIETNAM': 'HAN',
  
  'HO CHI MINH': 'SGN',
  'HO CHI MINH CITY': 'SGN',
  'HO CHI MINH, VIETNAM': 'SGN',
  'SAIGON': 'SGN',
  
  'MUMBAI': 'BOM',
  'MUMBAI, INDIA': 'BOM',
  'MUMBAI, IN': 'BOM',
  'BOMBAY': 'BOM',
  
  'DELHI': 'DEL',
  'DELHI, INDIA': 'DEL',
  'DELHI, IN': 'DEL',
  'NEW DELHI': 'DEL',
  
  'BANGALORE': 'BLR',
  'BANGALORE, INDIA': 'BLR',
  'BANGALORE, IN': 'BLR',
  
  'COLOMBO': 'CMB',
  'COLOMBO, SRI LANKA': 'CMB',
  'COLOMBO, LK': 'CMB',
  
  'KATHMANDU': 'KTM',
  'KATHMANDU, NEPAL': 'KTM',
  'KATHMANDU, NP': 'KTM',
  
  'MALE': 'MLE',
  'MALE, MALDIVES': 'MLE',
  'MALDIVES': 'MLE',
  
  'SIEM REAP': 'REP',
  'SIEM REAP, CAMBODIA': 'REP',
  
  'LUANG PRABANG': 'LPQ',
  'LUANG PRABANG, LAOS': 'LPQ',
  
  'YANGON': 'RGN',
  'YANGON, MYANMAR': 'RGN',
  
  'DHAKA': 'DAC',
  'DHAKA, BANGLADESH': 'DAC',
  
  'ISLAMABAD': 'ISB',
  'ISLAMABAD, PAKISTAN': 'ISB',
  
  'KARACHI': 'KHI',
  'KARACHI, PAKISTAN': 'KHI',
  
  'LAHORE': 'LHE',
  'LAHORE, PAKISTAN': 'LHE',
  
  'KABUL': 'KBL',
  'KABUL, AFGHANISTAN': 'KBL',
  
  'TASHKENT': 'TAS',
  'TASHKENT, UZBEKISTAN': 'TAS',
  'TASHKENT, UZ': 'TAS',
  'UZBEKISTAN': 'TAS',
  
  'ALMATY': 'ALA',
  'ALMATY, KAZAKHSTAN': 'ALA',
  'ALMATY, KZ': 'ALA',
  'KAZAKHSTAN': 'ALA',
  
  'BISHKEK': 'FRU',
  'BISHKEK, KYRGYZSTAN': 'FRU',
  
  'DUSHANBE': 'DYU',
  'DUSHANBE, TAJIKISTAN': 'DYU',
  
  'ASHGABAT': 'ASB',
  'ASHGABAT, TURKMENISTAN': 'ASB',
  
  'YEREVAN': 'EVN',
  'YEREVAN, ARMENIA': 'EVN',
  'YEREVAN, AM': 'EVN',
  'ARMENIA': 'EVN',
  
  'TBILISI': 'TBS',
  'TBILISI, GEORGIA': 'TBS',
  'TBILISI, GE': 'TBS',
  'GEORGIA': 'TBS',
  
  'BAKU': 'GYD',
  'BAKU, AZERBAIJAN': 'GYD',
  'BAKU, AZ': 'GYD',
  'AZERBAIJAN': 'GYD',
  
  'TEHRAN': 'IKA',
  'TEHRAN, IRAN': 'IKA',
  
  'BAGHDAD': 'BGW',
  'BAGHDAD, IRAQ': 'BGW',
  
  'AMMAN': 'AMM',
  'AMMAN, JORDAN': 'AMM',
  'AMMAN, JO': 'AMM',
  'JORDAN': 'AMM',
  
  'BEIRUT': 'BEY',
  'BEIRUT, LEBANON': 'BEY',
  'BEIRUT, LB': 'BEY',
  'LEBANON': 'BEY',
  
  'DAMASCUS': 'DAM',
  'DAMASCUS, SYRIA': 'DAM',
  
  'KUWAIT CITY': 'KWI',
  'KUWAIT CITY, KUWAIT': 'KWI',
  
  'MANAMA': 'BAH',
  'MANAMA, BAHRAIN': 'BAH',
  
  'DOHA': 'DOH',
  'DOHA, QATAR': 'DOH',
  'DOHA, QA': 'DOH',
  'QATAR': 'DOH',
  
  'ABU DHABI': 'AUH',
  'ABU DHABI, UAE': 'AUH',
  'ABU DHABI, UNITED ARAB EMIRATES': 'AUH',
  
  'DUBAI': 'DXB',
  'DUBAI, UAE': 'DXB',
  'DUBAI, UNITED ARAB EMIRATES': 'DXB',
  'UAE': 'DXB',
  'UNITED ARAB EMIRATES': 'DXB',
  
  'MUSCAT': 'MCT',
  'MUSCAT, OMAN': 'MCT',
  
  'SANA\'A': 'SAH',
  'SANAA': 'SAH',
  'SANA\'A, YEMEN': 'SAH',
  
  'RIYADH': 'RUH',
  'RIYADH, SAUDI ARABIA': 'RUH',
  'RIYADH, SA': 'RUH',
  'SAUDI ARABIA': 'RUH',
  
  'JEDDAH': 'JED',
  'JEDDAH, SAUDI ARABIA': 'JED',
  'JEDDAH, SA': 'JED',
  
  'MECCA': 'JED',
  'MECCA, SAUDI ARABIA': 'JED',
  
  'MEDINA': 'MED',
  'MEDINA, SAUDI ARABIA': 'MED',
  
  'DAMMAM': 'DMM',
  'DAMMAM, SAUDI ARABIA': 'DMM',
  
  'TABUK': 'TUU',
  'TABUK, SAUDI ARABIA': 'TUU',
  
  'TAIF': 'TIF',
  'TAIF, SAUDI ARABIA': 'TIF',
  
  'KHAMIS MUSHAIT': 'AHB',
  'KHAMIS MUSHAIT, SAUDI ARABIA': 'AHB',
  
  'HAIL': 'HAS',
  'HAIL, SAUDI ARABIA': 'HAS',
  
  'NAJRAN': 'EAM',
  'NAJRAN, SAUDI ARABIA': 'EAM',
  
  'JIZAN': 'GIZ',
  'JIZAN, SAUDI ARABIA': 'GIZ',
  'AL BAH': 'ABT',
  'AL BAH, SAUDI ARABIA': 'ABT',
  
  // ===========================================
  // 🌏 Asia - Additional Cities
  // ===========================================
  'KOH SAMUI': 'USM',
  'KOH SAMUI, THAILAND': 'USM',
  
  'KRABI': 'KBV',
  'KRABI, THAILAND': 'KBV',
  
  'LANGKAWI': 'LGK',
  'LANGKAWI, MALAYSIA': 'LGK',
  
  'PENANG': 'PEN',
  'PENANG, MALAYSIA': 'PEN',
  
  'BORACAY': 'MPH',
  'BORACAY, PHILIPPINES': 'MPH',
  
  'PALAWAN': 'PPS',
  'PALAWAN, PHILIPPINES': 'PPS',
  
  'EL NIDO': 'ENI',
  'EL NIDO, PHILIPPINES': 'ENI',
  
  'CORON': 'USU',
  'CORON, PHILIPPINES': 'USU',
  
  'SIARGAO': 'IAO',
  'SIARGAO, PHILIPPINES': 'IAO',
  
  'BOHOL': 'TAG',
  'BOHOL, PHILIPPINES': 'TAG',
  
  'SIQUIJOR': 'SGQ',
  'SIQUIJOR, PHILIPPINES': 'SGQ',
  
  'CAMIGUIN': 'CGM',
  'CAMIGUIN, PHILIPPINES': 'CGM',
  
  'ROMBLON': 'TBH',
  'ROMBLON, PHILIPPINES': 'TBH',
  
  'MARINDUQUE': 'MRQ',
  'MARINDUQUE, PHILIPPINES': 'MRQ',
  
  'MINDORO': 'MBO',
  'MINDORO, PHILIPPINES': 'MBO',
  
  'LUZON': 'MNL',
  'LUZON, PHILIPPINES': 'MNL',
  
  'VISAYAS': 'CEB',
  'VISAYAS, PHILIPPINES': 'CEB',
  
  'MINDANAO': 'DVO',
  'MINDANAO, PHILIPPINES': 'DVO',
  
  'BANTAYAN ISLAND': 'BNU',
  'BANTAYAN ISLAND, PHILIPPINES': 'BNU',
  
  'MALAPASCUA': 'CEB',
  'MALAPASCUA, PHILIPPINES': 'CEB',
  
  'APO ISLAND': 'DGT',
  'APO ISLAND, PHILIPPINES': 'DGT',
  
  'DUMAGUETE': 'DGT',
  'DUMAGUETE, PHILIPPINES': 'DGT',
  
  'NEGROS': 'BCD',
  'NEGROS, PHILIPPINES': 'BCD',
  
  'PANAY': 'ILO',
  'PANAY, PHILIPPINES': 'ILO',
  
  'GUIMARAS': 'ILO',
  'GUIMARAS, PHILIPPINES': 'ILO',
  
  'MASBATE': 'MBT',
  'MASBATE, PHILIPPINES': 'MBT',
  
  'SAMAR': 'TAC',
  'SAMAR, PHILIPPINES': 'TAC',
  
  'LEYTE': 'TAC',
  'LEYTE, PHILIPPINES': 'TAC',
  
  'BILIRAN': 'TAC',
  'BILIRAN, PHILIPPINES': 'TAC',
  
  'CALICOAN ISLAND': 'TAC',
  'CALICOAN ISLAND, PHILIPPINES': 'TAC',
  
  'HOMONHON ISLAND': 'TAC',
  'HOMONHON ISLAND, PHILIPPINES': 'TAC',
  
  'DINAGAT ISLANDS': 'DGT',
  'DINAGAT ISLANDS, PHILIPPINES': 'DGT',
  
  'SURIGAO': 'SUG',
  'SURIGAO, PHILIPPINES': 'SUG',
  
  'BUCAS GRANDE': 'SUG',
  'BUCAS GRANDE, PHILIPPINES': 'SUG',
  
  'SOCORRO': 'SUG',
  'SOCORRO, PHILIPPINES': 'SUG',
  
  'GENERAL LUNA': 'SUG',
  'GENERAL LUNA, PHILIPPINES': 'SUG',
  
  'DEL CARMEN': 'SUG',
  'DEL CARMEN, PHILIPPINES': 'SUG',
  
  'SANTA MONICA': 'SUG',
  'SANTA MONICA, PHILIPPINES': 'SUG',
  
  'SAN BENITO': 'SUG',
  'SAN BENITO, PHILIPPINES': 'SUG',
  
  'PILAR': 'SUG',
  'PILAR, PHILIPPINES': 'SUG',
  
  'SAN ISIDRO': 'SUG',
  'SAN ISIDRO, PHILIPPINES': 'SUG',
  
  'DAPA': 'SUG',
  'DAPA, PHILIPPINES': 'SUG',
  
  'CLAVER': 'SUG',
  'CLAVER, PHILIPPINES': 'SUG',
  
  'PLACER': 'SUG',
  'PLACER, PHILIPPINES': 'SUG',
  
  'SISON': 'SUG',
  'SISON, PHILIPPINES': 'SUG',
  
  'TAGANA-AN': 'SUG',
  'TAGANA-AN, PHILIPPINES': 'SUG',
  
  'TUBOD': 'SUG',
  'TUBOD, PHILIPPINES': 'SUG',
  
  'MAINIT': 'SUG',
  'MAINIT, PHILIPPINES': 'SUG',
  
  'MALIMONO': 'SUG',
  'MALIMONO, PHILIPPINES': 'SUG',
  
  'SAN FRANCISCO': 'SUG',
  'SAN FRANCISCO, PHILIPPINES': 'SUG',
  
  'ANAO-AON': 'SUG',
  'ANAO-AON, PHILIPPINES': 'SUG',
  
  'SAN JOSE': 'SJI',
  'SAN JOSE, PHILIPPINES': 'SJI',
  
  'LORETO': 'SUG',
  'LORETO, PHILIPPINES': 'SUG',
  
  'BURGOS': 'SUG',
  'BURGOS, PHILIPPINES': 'SUG',

  // ===========================================
  // 🌎 Americas (Non-USA/Canada) - Additional Cities
  // ===========================================
  'GUADALAJARA': 'GDL',
  'GUADALAJARA, MEXICO': 'GDL',
  'GUADALAJARA, MX': 'GDL',
  
  'MONTERREY': 'MTY',
  'MONTERREY, MEXICO': 'MTY',
  'MONTERREY, MX': 'MTY',
  
  'PUERTO VALLARTA': 'PVR',
  'PUERTO VALLARTA, MEXICO': 'PVR',
  
  'CABO SAN LUCAS': 'SJD',
  'CABO SAN LUCAS, MEXICO': 'SJD',
  'LOS CABOS': 'SJD',
  
  'MERIDA': 'MID',
  'MERIDA, MEXICO': 'MID',
  
  'OAXACA': 'OAX',
  'OAXACA, MEXICO': 'OAX',
  
  'PUEBLA': 'PBC',
  'PUEBLA, MEXICO': 'PBC',
  
  'SAN MIGUEL DE ALLENDE': 'BJX',
  'SAN MIGUEL DE ALLENDE, MEXICO': 'BJX',
  
  'GUANAJUATO': 'BJX',
  'GUANAJUATO, MEXICO': 'BJX',
  
  'MORELIA': 'MLM',
  'MORELIA, MEXICO': 'MLM',
  
  'ACAPULCO': 'ACA',
  'ACAPULCO, MEXICO': 'ACA',
  
  'MAZATLAN': 'MZT',
  'MAZATLAN, MEXICO': 'MZT',
  
  'LA PAZ': 'LAP',
  'LA PAZ, MEXICO': 'LAP',
  
  'ENSENADA': 'TIJ',
  'ENSENADA, MEXICO': 'TIJ',
  
  'ROSARITO': 'TIJ',
  'ROSARITO, MEXICO': 'TIJ',
  
  'SAN JOSE DEL CABO': 'SJD',
  'SAN JOSE DEL CABO, MEXICO': 'SJD',
  
  'TODOS SANTOS': 'SJD',
  'TODOS SANTOS, MEXICO': 'SJD',
  
  'LORETO': 'LTO',
  'LORETO, MEXICO': 'LTO',
  
  'MULEGE': 'GUB',
  'MULEGE, MEXICO': 'GUB',
  
  'GUERRERO NEGRO': 'GUB',
  'GUERRERO NEGRO, MEXICO': 'GUB',
  
  'SANTA ROSALIA': 'GUB',
  'SANTA ROSALIA, MEXICO': 'GUB',
  
  'SAN IGNACIO': 'GUB',
  'SAN IGNACIO, MEXICO': 'GUB',
  
  'CIUDAD CONSTITUCION': 'LAP',
  'CIUDAD CONSTITUCION, MEXICO': 'LAP',
  
  'LA VENTANA': 'LAP',
  'LA VENTANA, MEXICO': 'LAP',
  
  'LOS BARRILES': 'LAP',
  'LOS BARRILES, MEXICO': 'LAP',
  
  'BUENA VISTA': 'LAP',
  'BUENA VISTA, MEXICO': 'LAP',
  
  'MIRAFLORES': 'LAP',
  'MIRAFLORES, MEXICO': 'LAP',
  
  'SANTIAGO': 'SJD',
  'SANTIAGO, MEXICO': 'SJD',
  
  'RIO DE JANEIRO': 'GIG',
  'RIO DE JANEIRO, BRAZIL': 'GIG',
  'RIO DE JANEIRO, BR': 'GIG',
  'RIO': 'GIG',
  
  'SAO PAULO': 'GRU',
  'SAO PAULO, BRAZIL': 'GRU',
  'SAO PAULO, BR': 'GRU',
  'BRAZIL': 'GRU',
  
  'BUENOS AIRES': 'EZE',
  'BUENOS AIRES, ARGENTINA': 'EZE',
  'BUENOS AIRES, AR': 'EZE',
  'ARGENTINA': 'EZE',
  
  'SANTIAGO': 'SCL',
  'SANTIAGO, CHILE': 'SCL',
  'SANTIAGO, CL': 'SCL',
  'CHILE': 'SCL',
  
  'LIMA': 'LIM',
  'LIMA, PERU': 'LIM',
  'LIMA, PE': 'LIM',
  'PERU': 'LIM',
  
  'CUSCO': 'CUZ',
  'CUSCO, PERU': 'CUZ',
  'CUSCO, PE': 'CUZ',
  'MACHU PICCHU': 'CUZ',
  
  'BOGOTA': 'BOG',
  'BOGOTA, COLOMBIA': 'BOG',
  'BOGOTA, CO': 'BOG',
  'COLOMBIA': 'BOG',
  
  'CARTAGENA': 'CTG',
  'CARTAGENA, COLOMBIA': 'CTG',
  'CARTAGENA, CO': 'CTG',
  
  'QUITO': 'UIO',
  'QUITO, ECUADOR': 'UIO',
  'QUITO, EC': 'UIO',
  'ECUADOR': 'UIO',
  
  'LA PAZ': 'LPB',
  'LA PAZ, BOLIVIA': 'LPB',
  'LA PAZ, BO': 'LPB',
  'BOLIVIA': 'LPB',
  
  'ASUNCION': 'ASU',
  'ASUNCION, PARAGUAY': 'ASU',
  'ASUNCION, PY': 'ASU',
  
  'MONTEVIDEO': 'MVD',
  'MONTEVIDEO, URUGUAY': 'MVD',
  'MONTEVIDEO, UY': 'MVD',
  'URUGUAY': 'MVD',
  
  'CARACAS': 'CCS',
  'CARACAS, VENEZUELA': 'CCS',
  'CARACAS, VE': 'CCS',
  
  'PANAMA CITY': 'PTY',
  'PANAMA CITY, PANAMA': 'PTY',
  'PANAMA': 'PTY',
  
  'SAN JOSE': 'SJO',
  'SAN JOSE, COSTA RICA': 'SJO',
  'SAN JOSE, CR': 'SJO',
  'COSTA RICA': 'SJO',
  
  'GUATEMALA CITY': 'GUA',
  'GUATEMALA CITY, GUATEMALA': 'GUA',
  'GUATEMALA': 'GUA',
  
  'SAN SALVADOR': 'SAL',
  'SAN SALVADOR, EL SALVADOR': 'SAL',
  'EL SALVADOR': 'SAL',
  
  'MANAGUA': 'MGA',
  'MANAGUA, NICARAGUA': 'MGA',
  'NICARAGUA': 'MGA',
  
  'SAN PEDRO SULA': 'SAP',
  'SAN PEDRO SULA, HONDURAS': 'SAP',
  'HONDURAS': 'SAP',
  
  'SANTO DOMINGO': 'SDQ',
  'SANTO DOMINGO, DOMINICAN REPUBLIC': 'SDQ',
  'DOMINICAN REPUBLIC': 'SDQ',
  
  'PUNTA CANA': 'PUJ',
  'PUNTA CANA, DOMINICAN REPUBLIC': 'PUJ',
  
  'HAVANA': 'HAV',
  'HAVANA, CUBA': 'HAV',
  'HAVANA, CU': 'HAV',
  'CUBA': 'HAV',
  
  'KINGSTON': 'KIN',
  'KINGSTON, JAMAICA': 'KIN',
  'JAMAICA': 'KIN',
  
  'NASSAU': 'NAS',
  'NASSAU, BAHAMAS': 'NAS',
  'BAHAMAS': 'NAS',
  
  'PORT OF SPAIN': 'POS',
  'PORT OF SPAIN, TRINIDAD AND TOBAGO': 'POS',
  
  'BRIDGETOWN': 'BGI',
  'BRIDGETOWN, BARBADOS': 'BGI',
  
  'CASTRIES': 'SLU',
  'CASTRIES, SAINT LUCIA': 'SLU',
  
  'ST. GEORGE\'S': 'GND',
  'ST GEORGE\'S': 'GND',
  'ST. GEORGE\'S, GRENADA': 'GND',
  
  'KINGSTOWN': 'SVD',
  'KINGSTOWN, SAINT VINCENT AND THE GRENADINES': 'SVD',
  
  'ROAD TOWN': 'EIS',
  'ROAD TOWN, BRITISH VIRGIN ISLANDS': 'EIS',
  
  'CHARLOTTE AMALIE': 'STT',
  'CHARLOTTE AMALIE, US VIRGIN ISLANDS': 'STT',
  
  'SAN JUAN': 'SJU',
  'SAN JUAN, PUERTO RICO': 'SJU',
  
  'PONCE': 'PSE',
  'PONCE, PUERTO RICO': 'PSE',
  
  'MAYAGUEZ': 'MAZ',
  'MAYAGUEZ, PUERTO RICO': 'MAZ',
  
  'ARECIBO': 'ARE',
  'ARECIBO, PUERTO RICO': 'ARE',
  
  'CAGUAS': 'CGU',
  'CAGUAS, PUERTO RICO': 'CGU',
  
  'BAYAMON': 'SJU',
  'BAYAMON, PUERTO RICO': 'SJU',
  
  'CAROLINA': 'SJU',
  'CAROLINA, PUERTO RICO': 'SJU',
  
  'GUAYNABO': 'SJU',
  'GUAYNABO, PUERTO RICO': 'SJU',
  
  'TOA BAJA': 'SJU',
  'TOA BAJA, PUERTO RICO': 'SJU',
  
  'DORADO': 'SJU',
  'DORADO, PUERTO RICO': 'SJU',
  
  'VEGA BAJA': 'SJU',
  'VEGA BAJA, PUERTO RICO': 'SJU',
  
  'MANATI': 'SJU',
  'MANATI, PUERTO RICO': 'SJU',
  
  'BARCELONETA': 'SJU',
  'BARCELONETA, PUERTO RICO': 'SJU',
  
  'FLORIDA': 'SJU',
  'FLORIDA, PUERTO RICO': 'SJU',
  
  'CIALES': 'SJU',
  'CIALES, PUERTO RICO': 'SJU',
  
  'MOROVIS': 'SJU',
  'MOROVIS, PUERTO RICO': 'SJU',
  
  'COROZAL': 'SJU',
  'COROZAL, PUERTO RICO': 'SJU',
  
  'NARANJITO': 'SJU',
  'NARANJITO, PUERTO RICO': 'SJU',
  
  'TOA ALTA': 'SJU',
  'TOA ALTA, PUERTO RICO': 'SJU',
  
  'CANOVANAS': 'SJU',
  'CANOVANAS, PUERTO RICO': 'SJU',
  
  'LOIZA': 'SJU',
  'LOIZA, PUERTO RICO': 'SJU',
  
  'RIO GRANDE': 'SJU',
  'RIO GRANDE, PUERTO RICO': 'SJU',
  
  'LUQUILLO': 'SJU',
  'LUQUILLO, PUERTO RICO': 'SJU',
  
  'FAJARDO': 'FAJ',
  'FAJARDO, PUERTO RICO': 'FAJ',
  
  'CEIBA': 'FAJ',
  'CEIBA, PUERTO RICO': 'FAJ',
  
  'NAGUABO': 'FAJ',
  'NAGUABO, PUERTO RICO': 'FAJ',
  
  'HUMACAO': 'HUC',
  'HUMACAO, PUERTO RICO': 'HUC',
  
  'YABUCOA': 'HUC',
  'YABUCOA, PUERTO RICO': 'HUC',
  
  'MAUNABO': 'HUC',
  'MAUNABO, PUERTO RICO': 'HUC',
  
  'PATILLAS': 'HUC',
  'PATILLAS, PUERTO RICO': 'HUC',
  
  'ARROYO': 'HUC',
  'ARROYO, PUERTO RICO': 'HUC',
  
  'GUAYAMA': 'HUC',
  'GUAYAMA, PUERTO RICO': 'HUC',
  
  'SALINAS': 'HUC',
  'SALINAS, PUERTO RICO': 'HUC',
  
  'SANTA ISABEL': 'HUC',
  'SANTA ISABEL, PUERTO RICO': 'HUC',
  
  'JUANA DIAZ': 'HUC',
  'JUANA DIAZ, PUERTO RICO': 'HUC',
  
  'PENUelas': 'HUC',
  'PENUelas, PUERTO RICO': 'HUC',
  
  'ADJUNTAS': 'HUC',
  'ADJUNTAS, PUERTO RICO': 'HUC',
  
  'UTUADO': 'HUC',
  'UTUADO, PUERTO RICO': 'HUC',
  
  'LARES': 'HUC',
  'LARES, PUERTO RICO': 'HUC',
  
  'MARICAO': 'HUC',
  'MARICAO, PUERTO RICO': 'HUC',
  
  'SAN GERMAN': 'HUC',
  'SAN GERMAN, PUERTO RICO': 'HUC',
  
  'SABANA GRANDE': 'HUC',
  'SABANA GRANDE, PUERTO RICO': 'HUC',
  
  'YAUCO': 'HUC',
  'YAUCO, PUERTO RICO': 'HUC',
  
  'GUANICA': 'HUC',
  'GUANICA, PUERTO RICO': 'HUC',
  
  'LAJAS': 'HUC',
  'LAJAS, PUERTO RICO': 'HUC',
  
  'CABO ROJO': 'HUC',
  'CABO ROJO, PUERTO RICO': 'HUC',
  
  'HORMIGUEROS': 'HUC',
  'HORMIGUEROS, PUERTO RICO': 'HUC',
  
  'ANASCO': 'HUC',
  'ANASCO, PUERTO RICO': 'HUC',
  
  'RINCON': 'HUC',
  'RINCON, PUERTO RICO': 'HUC',
  
  'AGUADA': 'HUC',
  'AGUADA, PUERTO RICO': 'HUC',
  
  'AGUADILLA': 'BQN',
  'AGUADILLA, PUERTO RICO': 'BQN',
  
  'MOCA': 'BQN',
  'MOCA, PUERTO RICO': 'BQN',
  
  'ISABELA': 'BQN',
  'ISABELA, PUERTO RICO': 'BQN',
  
  'QUEBRADILLAS': 'BQN',
  'QUEBRADILLAS, PUERTO RICO': 'BQN',
  
  'CAMUY': 'BQN',
  'CAMUY, PUERTO RICO': 'BQN',
  
  'HATILLO': 'BQN',
  'HATILLO, PUERTO RICO': 'BQN',

  // ===========================================
  // 🌍 Africa & Middle East - Additional Cities
  // ===========================================
  'CAIRO': 'CAI',
  'CAIRO, EGYPT': 'CAI',
  'CAIRO, EG': 'CAI',
  'EGYPT': 'CAI',
  
  'MARRAKECH': 'RAK',
  'MARRAKECH, MOROCCO': 'RAK',
  'MARRAKECH, MA': 'RAK',
  'MOROCCO': 'RAK',
  
  'CASABLANCA': 'CMN',
  'CASABLANCA, MOROCCO': 'CMN',
  'CASABLANCA, MA': 'CMN',
  
  'TUNIS': 'TUN',
  'TUNIS, TUNISIA': 'TUN',
  'TUNIS, TN': 'TUN',
  'TUNISIA': 'TUN',
  
  'JOHANNESBURG': 'JNB',
  'JOHANNESBURG, SOUTH AFRICA': 'JNB',
  'JOHANNESBURG, ZA': 'JNB',
  'SOUTH AFRICA': 'JNB',
  
  'CAPE TOWN': 'CPT',
  'CAPE TOWN, SOUTH AFRICA': 'CPT',
  'CAPE TOWN, ZA': 'CPT',
  
  'NAIROBI': 'NBO',
  'NAIROBI, KENYA': 'NBO',
  'NAIROBI, KE': 'NBO',
  'KENYA': 'NBO',
  
  'MOMBASA': 'MBA',
  'MOMBASA, KENYA': 'MBA',
  'MOMBASA, KE': 'MBA',
  
  'ADDIS ABABA': 'ADD',
  'ADDIS ABABA, ETHIOPIA': 'ADD',
  'ADDIS ABABA, ET': 'ADD',
  'ETHIOPIA': 'ADD',
  
  'LAGOS': 'LOS',
  'LAGOS, NIGERIA': 'LOS',
  'LAGOS, NG': 'LOS',
  'NIGERIA': 'LOS',
  
  'ACCRA': 'ACC',
  'ACCRA, GHANA': 'ACC',
  'ACCRA, GH': 'ACC',
  'GHANA': 'ACC',
  
  'DAKAR': 'DSS',
  'DAKAR, SENEGAL': 'DSS',
  'DAKAR, SN': 'DSS',
  'SENEGAL': 'DSS',
  
  'DAR ES SALAAM': 'DAR',
  'DAR ES SALAAM, TANZANIA': 'DAR',
  
  'ZANZIBAR': 'ZNZ',
  'ZANZIBAR, TANZANIA': 'ZNZ',
  'STONE TOWN': 'ZNZ',
  
  'KIGALI': 'KGL',
  'KIGALI, RWANDA': 'KGL',
  
  'KAMPALA': 'EBB',
  'KAMPALA, UGANDA': 'EBB',
  
  'LUSAKA': 'LUN',
  'LUSAKA, ZAMBIA': 'LUN',
  
  'HARARE': 'HRE',
  'HARARE, ZIMBABWE': 'HRE',
  
  'GABORONE': 'GBE',
  'GABORONE, BOTSWANA': 'GBE',
  
  'WINDHOEK': 'WDH',
  'WINDHOEK, NAMIBIA': 'WDH',
  
  'MAPUTO': 'MPM',
  'MAPUTO, MOZAMBIQUE': 'MPM',
  
  'ANTANANARIVO': 'TNR',
  'ANTANANARIVO, MADAGASCAR': 'TNR',
  
  'PORT LOUIS': 'MRU',
  'PORT LOUIS, MAURITIUS': 'MRU',
  
  'VICTORIA': 'SEZ',
  'VICTORIA, SEYCHELLES': 'SEZ',
  
  'TEL AVIV': 'TLV',
  'TEL AVIV, ISRAEL': 'TLV',
  'TEL AVIV, IL': 'TLV',
  'ISRAEL': 'TLV',
  
  'JERUSALEM': 'TLV',
  'JERUSALEM, ISRAEL': 'TLV',

  // ===========================================
  // 🌏 Oceania - Additional Cities
  // ===========================================
  'SYDNEY': 'SYD',
  'SYDNEY, AUSTRALIA': 'SYD',
  'SYDNEY, AU': 'SYD',
  'AUSTRALIA': 'SYD',
  
  'MELBOURNE': 'MEL',
  'MELBOURNE, AUSTRALIA': 'MEL',
  'MELBOURNE, AU': 'MEL',
  
  'BRISBANE': 'BNE',
  'BRISBANE, AUSTRALIA': 'BNE',
  'BRISBANE, AU': 'BNE',
  
  'PERTH': 'PER',
  'PERTH, AUSTRALIA': 'PER',
  'PERTH, AU': 'PER',
  
  'ADELAIDE': 'ADL',
  'ADELAIDE, AUSTRALIA': 'ADL',
  'ADELAIDE, AU': 'ADL',
  
  'GOLD COAST': 'OOL',
  'GOLD COAST, AUSTRALIA': 'OOL',
  'GOLD COAST, AU': 'OOL',
  
  'CAIRNS': 'CNS',
  'CAIRNS, AUSTRALIA': 'CNS',
  'CAIRNS, AU': 'CNS',
  'GREAT BARRIER REEF': 'CNS',
  
  'AUCKLAND': 'AKL',
  'AUCKLAND, NEW ZEALAND': 'AKL',
  'AUCKLAND, NZ': 'AKL',
  'NEW ZEALAND': 'AKL',
  
  'WELLINGTON': 'WLG',
  'WELLINGTON, NEW ZEALAND': 'WLG',
  'WELLINGTON, NZ': 'WLG',
  
  'CHRISTCHURCH': 'CHC',
  'CHRISTCHURCH, NEW ZEALAND': 'CHC',
  'CHRISTCHURCH, NZ': 'CHC',
  
  'QUEENSTOWN': 'ZQN',
  'QUEENSTOWN, NEW ZEALAND': 'ZQN',
  'QUEENSTOWN, NZ': 'ZQN',
  
  'FIJI': 'NAN',
  'NADI': 'NAN',
  'NADI, FIJI': 'NAN',
  
  'BORA BORA': 'BOB',
  'BORA BORA, FRENCH POLYNESIA': 'BOB',
  
  'TAHITI': 'PPT',
  'PAPEETE': 'PPT',
  'PAPEETE, FRENCH POLYNESIA': 'PPT',
  
  'MOOREA': 'PPT',
  'MOOREA, FRENCH POLYNESIA': 'PPT',
  
  'RAROTONGA': 'RAR',
  'RAROTONGA, COOK ISLANDS': 'RAR',
  
  'AITUTAKI': 'AIT',
  'AITUTAKI, COOK ISLANDS': 'AIT',
  
  'NUKU\'ALOF': 'TBU',
  'NUKU ALOFA': 'TBU',
  'NUKU\'ALOFA, TONGA': 'TBU',
  
  'APIA': 'APW',
  'APIA, SAMOA': 'APW',
  
  'PORT VILA': 'VLI',
  'PORT VILA, VANUATU': 'VLI',
  
  'HONIARA': 'HIR',
  'HONIARA, SOLOMON ISLANDS': 'HIR',
  
  'PORT MORESBY': 'POM',
  'PORT MORESBY, PAPUA NEW GUINEA': 'POM',
  
  'LAUTOKA': 'LTK',
  'LAUTOKA, FIJI': 'LTK',
  
  'SUVA': 'SUV',
  'SUVA, FIJI': 'SUV',
  
  'DENARAU': 'NAN',
  'DENARAU, FIJI': 'NAN',
  
  'CORAL COAST': 'NAN',
  'CORAL COAST, FIJI': 'NAN',
  
  'PACIFIC HARBOUR': 'SUV',
  'PACIFIC HARBOUR, FIJI': 'SUV',
  
  'BEQA': 'SUV',
  'BEQA, FIJI': 'SUV',
  
  'KADAVU': 'KDV',
  'KADAVU, FIJI': 'KDV',
  
  'TAVEUNI': 'TVU',
  'TAVEUNI, FIJI': 'TVU',
  
  'VANUA LEVU': 'LBS',
  'VANUA LEVU, FIJI': 'LBS',
  
  'SAVUSAVU': 'SVU',
  'SAVUSAVU, FIJI': 'SVU',
  
  'LABASA': 'LBS',
  'LABASA, FIJI': 'LBS',
  
  'YASAWA ISLANDS': 'NAN',
  'YASAWA ISLANDS, FIJI': 'NAN',
  
  'MAMANUCA ISLANDS': 'NAN',
  'MAMANUCA ISLANDS, FIJI': 'NAN',
  
  'CASTAWAY ISLAND': 'NAN',
  'CASTAWAY ISLAND, FIJI': 'NAN',
  
  'TOKORIKI': 'NAN',
  'TOKORIKI, FIJI': 'NAN',
  
  'MONURIKI': 'NAN',
  'MONURIKI, FIJI': 'NAN',
  
  'MANA ISLAND': 'MNF',
  'MANA ISLAND, FIJI': 'MNF',
  
  'TREASURE ISLAND': 'NAN',
  'TREASURE ISLAND, FIJI': 'NAN',
  
  'BEACHCOMBER': 'NAN',
  'BEACHCOMBER, FIJI': 'NAN',
  
  'SOUTH SEA ISLAND': 'NAN',
  'SOUTH SEA ISLAND, FIJI': 'NAN',
  
  'PLANTATION ISLAND': 'NAN',
  'PLANTATION ISLAND, FIJI': 'NAN',
  
  'LIKULIKU LAGOON RESORT': 'NAN',
  'LIKULIKU LAGOON RESORT, FIJI': 'NAN',
  
  'MATAMANO': 'NAN',
  'MATAMANO, FIJI': 'NAN',

  // ===========================================
  // 🏝️ Popular Island Destinations
  // ===========================================
  'MALDIVES': 'MLE',
  'MALE, MALDIVES': 'MLE',
  
  'SEYCHELLES': 'SEZ',
  'MAHE': 'SEZ',
  'MAHE, SEYCHELLES': 'SEZ',
  
  'MAURITIUS': 'MRU',
  'PORT LOUIS': 'MRU',
  'PORT LOUIS, MAURITIUS': 'MRU',
  
  'ZANZIBAR': 'ZNZ',
  'ZANZIBAR, TANZANIA': 'ZNZ',
  'STONE TOWN': 'ZNZ',
  
  'SEYCHELLES': 'SEZ',
  
  'FIJI': 'NAN',
  'NADI, FIJI': 'NAN',
  
  'BORA BORA': 'BOB',
  'BORA BORA, FRENCH POLYNESIA': 'BOB',
  
  'TAHITI': 'PPT',
  'PAPEETE': 'PPT',
  'PAPEETE, FRENCH POLYNESIA': 'PPT',
  
  'HAWAII': 'HNL',
  'HONOLULU': 'HNL',
  'HONOLULU, HAWAII': 'HNL',
  'HONOLULU, HI': 'HNL',
  'OAHU': 'HNL',
  
  'MAUI': 'OGG',
  'MAUI, HAWAII': 'OGG',
  'KAHULUI': 'OGG',
  
  'BIG ISLAND': 'KOA',
  'KONA': 'KOA',
  'KONA, HAWAII': 'KOA',
  
  'KAUAI': 'LIH',
  'KAUAI, HAWAII': 'LIH',
  'LIHUE': 'LIH'
};

/**
 * Obtener código IATA para una ciudad
 * @param {string} location - Nombre de la ciudad
 * @returns {string|null} Código IATA o null si no se encuentra
 */
function getAirportCode(location) {
  if (!location) return null;
  
  var upper = String(location).toUpperCase().trim();
  
  // ✅ Buscar coincidencia exacta primero
  if (AIRPORT_CODES[upper]) {
    return AIRPORT_CODES[upper];
  }
  
  // ✅ Buscar por contiene (más flexible)
  for (var city in AIRPORT_CODES) {
    if (upper.includes(city)) {
      return AIRPORT_CODES[city];
    }
  }
  
  // ✅ Si ya es código IATA (3 letras mayúsculas), retornarlo
  if (/^[A-Z]{3}$/.test(upper)) {
    return upper;
  }
  
  // ✅ Fallback: intentar extraer código si formato es "Ciudad (XXX)"
  var codeMatch = upper.match(/\(([A-Z]{3})\)/);
  if (codeMatch && codeMatch[1]) {
    return codeMatch[1];
  }
  
  // ✅ Fallback final: retornar null para que el caller maneje el error
  return null;
}

/**
 * Obtener lista de todas las ciudades disponibles
 * @returns {string[]} Array de nombres de ciudades
 */
function getAvailableCities() {
  return Object.keys(AIRPORT_CODES)
    .filter(key => !/^[A-Z]{3}$/.test(key)) // Excluir códigos IATA puros
    .sort();
}

/**
 * Buscar ciudades por término
 * @param {string} searchTerm - Término de búsqueda
 * @returns {Array<{city: string, code: string}>} Resultados de búsqueda
 */
function searchCities(searchTerm) {
  if (!searchTerm) return [];
  
  var term = searchTerm.toUpperCase().trim();
  var results = [];
  
  for (var city in AIRPORT_CODES) {
    if (city.includes(term) || AIRPORT_CODES[city].includes(term)) {
      results.push({
        city: city,
        code: AIRPORT_CODES[city]
      });
    }
  }
  
  return results.slice(0, 20); // Limitar a 20 resultados
}

module.exports = {
  AIRPORT_CODES,
  getAirportCode,
  getAvailableCities,
  searchCities
};